package com.ecole.gestion_scolaire.student.service;
import com.ecole.gestion_scolaire.student.dto.*; import com.ecole.gestion_scolaire.student.entity.AuthorizedPickupPerson; import com.ecole.gestion_scolaire.student.repository.AuthorizedPickupPersonRepository; import com.ecole.gestion_scolaire.common.exception.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class AuthorizedPickupPersonService{
 private final AuthorizedPickupPersonRepository repo; private final StudentService students; public AuthorizedPickupPersonService(AuthorizedPickupPersonRepository r,StudentService s){repo=r;students=s;}
 public List<AuthorizedPickupPersonResponse> findByStudent(Long id){students.get(id);return repo.findByStudentIdOrderByLastNameAscFirstNameAsc(id).stream().map(this::map).toList();}
 @Transactional public AuthorizedPickupPersonResponse create(Long id,AuthorizedPickupPersonRequest r){validate(r);AuthorizedPickupPerson x=new AuthorizedPickupPerson();x.setStudent(students.get(id));apply(x,r);return map(repo.save(x));}
 @Transactional public AuthorizedPickupPersonResponse update(Long id,AuthorizedPickupPersonRequest r){validate(r);AuthorizedPickupPerson x=repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Personne autorisée introuvable : "+id));apply(x,r);return map(repo.save(x));}
 private void validate(AuthorizedPickupPersonRequest r){if(r.validFrom()!=null&&r.validUntil()!=null&&r.validUntil().isBefore(r.validFrom()))throw new BusinessRuleException("La date de fin de validité ne peut pas précéder la date de début.");}
 private void apply(AuthorizedPickupPerson x,AuthorizedPickupPersonRequest r){x.setFirstName(r.firstName().trim());x.setLastName(r.lastName().trim());x.setRelationship(r.relationship());x.setPhone(r.phone().trim());x.setIdentityDocumentNumber(r.identityDocumentNumber());x.setIssuedBy(r.issuedBy());x.setValidFrom(r.validFrom());x.setValidUntil(r.validUntil());x.setActive(r.active());}
 private AuthorizedPickupPersonResponse map(AuthorizedPickupPerson x){return new AuthorizedPickupPersonResponse(x.getId(),x.getStudent().getId(),x.getFirstName(),x.getLastName(),x.getRelationship(),x.getPhone(),x.getIdentityDocumentNumber(),x.getIssuedBy(),x.getValidFrom(),x.getValidUntil(),x.isActive());}
}
