package com.ecole.gestion_scolaire.finance.service;
import com.ecole.gestion_scolaire.finance.dto.discount.*; import com.ecole.gestion_scolaire.finance.entity.DiscountRule; import com.ecole.gestion_scolaire.finance.enums.*; import com.ecole.gestion_scolaire.finance.exception.*; import com.ecole.gestion_scolaire.finance.repository.*; import com.ecole.gestion_scolaire.registration.repository.StudentEnrollmentRepository; import com.ecole.gestion_scolaire.school.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.util.*;
@Service public class DiscountRuleService{
 private final DiscountRuleRepository repo;private final FeeTypeRepository fees;private final SchoolYearRepository years;private final CycleRepository cycles;private final LevelRepository levels;private final ClassGroupRepository classes;private final CampusRepository campuses;private final StudentEnrollmentRepository enrollments;private final DiscountService discounts;
 public DiscountRuleService(DiscountRuleRepository r,FeeTypeRepository f,SchoolYearRepository y,CycleRepository cy,LevelRepository l,ClassGroupRepository c,CampusRepository ca,StudentEnrollmentRepository e,DiscountService d){repo=r;fees=f;years=y;cycles=cy;levels=l;classes=c;campuses=ca;enrollments=e;discounts=d;}
 @Transactional(readOnly=true) public List<DiscountRuleResponse> list(Long yearId){return repo.findBySchoolYearIdOrderByPriorityDescIdAsc(yearId).stream().map(this::toResponse).toList();}
 @Transactional public DiscountRuleResponse create(DiscountRuleRequest r){if(repo.existsByCodeIgnoreCase(r.code().trim()))throw new FinanceBusinessException("Ce code de règle existe déjà.");validate(r);var x=new DiscountRule();apply(x,r);return toResponse(repo.save(x));}
 @Transactional public DiscountRuleResponse update(Long id,DiscountRuleRequest r){var x=repo.findById(id).orElseThrow(()->new FinanceNotFoundException("Règle de réduction introuvable."));validate(r);apply(x,r);return toResponse(repo.save(x));}
 @Transactional public DiscountApplicationResponse apply(Long id){var rule=repo.findById(id).orElseThrow(()->new FinanceNotFoundException("Règle de réduction introuvable."));if(!rule.isActive())throw new FinanceBusinessException("La règle est inactive.");int c=0;BigDecimal reduction=BigDecimal.ZERO,credit=BigDecimal.ZERO;for(var e:enrollments.findBySchoolYearIdOrderByIdAsc(rule.getSchoolYearId())){var r=discounts.reapplyEnrollment(e.getId());c+=r.chargesUpdated();reduction=reduction.add(r.totalReductionApplied());credit=credit.add(r.familyCreditCreated());}return new DiscountApplicationResponse(c,reduction,credit);}
 private void validate(DiscountRuleRequest r){if(!years.existsById(r.schoolYearId()))throw new FinanceNotFoundException("Année scolaire introuvable.");if(r.feeTypeId()!=null&&!fees.existsById(r.feeTypeId()))throw new FinanceNotFoundException("Type de frais introuvable.");if(r.cycleId()!=null&&!cycles.existsById(r.cycleId()))throw new FinanceNotFoundException("Cycle introuvable.");if(r.levelId()!=null&&!levels.existsById(r.levelId()))throw new FinanceNotFoundException("Niveau introuvable.");if(r.classGroupId()!=null&&!classes.existsById(r.classGroupId()))throw new FinanceNotFoundException("Classe introuvable.");if(r.campusId()!=null&&!campuses.existsById(r.campusId()))throw new FinanceNotFoundException("Campus introuvable.");try{DiscountType.valueOf(r.discountType().toUpperCase(Locale.ROOT));DiscountConditionType.valueOf((r.conditionType()==null?"ALWAYS":r.conditionType()).toUpperCase(Locale.ROOT));}catch(Exception e){throw new FinanceBusinessException("Type ou condition de réduction invalide.");}if(r.value()==null||r.value().signum()<0)throw new FinanceBusinessException("Valeur invalide.");if("PERCENTAGE".equalsIgnoreCase(r.discountType())&&r.value().compareTo(new BigDecimal("100"))>0)throw new FinanceBusinessException("Le pourcentage ne peut pas dépasser 100 %.");if("FAMILY_CHILD_RANK".equalsIgnoreCase(r.conditionType())&&(r.childRank()==null||r.childRank()<1))throw new FinanceBusinessException("Le rang de l'enfant est obligatoire pour une règle familiale.");if(r.validUntil()!=null&&r.validFrom()!=null&&r.validUntil().isBefore(r.validFrom()))throw new FinanceBusinessException("Période de validité invalide.");}
 private void apply(DiscountRule x,DiscountRuleRequest r){x.setSchoolYearId(r.schoolYearId());x.setCode(r.code().trim().toUpperCase(Locale.ROOT));x.setName(r.name().trim());x.setDiscountType(r.discountType().toUpperCase(Locale.ROOT));x.setValue(r.value());x.setFeeTypeId(r.feeTypeId());x.setPriority(r.priority()==null?0:r.priority());x.setRequiresApproval(Boolean.TRUE.equals(r.requiresApproval()));x.setActive(r.active()==null||r.active());x.setValidFrom(r.validFrom());x.setValidUntil(r.validUntil());x.setConditionType((r.conditionType()==null?"ALWAYS":r.conditionType()).toUpperCase(Locale.ROOT));x.setChildRank(r.childRank());x.setCycleId(r.cycleId());x.setLevelId(r.levelId());x.setClassGroupId(r.classGroupId());x.setCampusId(r.campusId());}
 private DiscountRuleResponse toResponse(DiscountRule x){return new DiscountRuleResponse(x.getId(),x.getSchoolYearId(),x.getCode(),x.getName(),x.getDiscountType(),x.getValue(),x.getFeeTypeId(),x.getPriority(),x.isRequiresApproval(),x.isActive(),x.getValidFrom(),x.getValidUntil(),x.getConditionType(),x.getChildRank(),x.getCycleId(),x.getLevelId(),x.getClassGroupId(),x.getCampusId());}
}
