package com.ecole.gestion_scolaire.attendance.service;
import com.ecole.gestion_scolaire.attendance.dto.*; import com.ecole.gestion_scolaire.attendance.entity.*; import com.ecole.gestion_scolaire.attendance.enums.*; import com.ecole.gestion_scolaire.attendance.repository.*; import com.ecole.gestion_scolaire.common.dto.PageResponse; import com.ecole.gestion_scolaire.common.exception.*; import com.ecole.gestion_scolaire.identity.entity.UserAccount; import com.ecole.gestion_scolaire.identity.repository.UserAccountRepository; import com.ecole.gestion_scolaire.registration.enums.EnrollmentStatus; import com.ecole.gestion_scolaire.registration.repository.StudentEnrollmentRepository; import com.ecole.gestion_scolaire.timetable.entity.ScheduleEntry; import com.ecole.gestion_scolaire.timetable.enums.*; import com.ecole.gestion_scolaire.timetable.repository.ScheduleEntryRepository;
import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*; import java.util.stream.Collectors;
@Service @Transactional public class StudentAttendanceService {
 private final ScheduleEntryRepository schedules; private final ClassSessionRepository sessions; private final StudentAttendanceRepository attendances; private final StudentEnrollmentRepository enrollments; private final UserAccountRepository users; private final AttendanceEmailService attendanceEmailService;
 public StudentAttendanceService(ScheduleEntryRepository a,ClassSessionRepository b,StudentAttendanceRepository c,StudentEnrollmentRepository d,UserAccountRepository e,AttendanceEmailService f){schedules=a;sessions=b;attendances=c;enrollments=d;users=e;attendanceEmailService=f;}
 @Transactional(readOnly=true) public List<ExpectedStudentAttendanceResponse> expected(LocalDate date,Long classGroupId,Long timeSlotId){
  var day=toSchoolDay(date.getDayOfWeek()); if(day==null)return List.of();
  var matches=schedules.findExpectedForAttendance(day,timeSlotId,date,ScheduleEntryStatus.ACTIVE).stream().filter(x->x.getTeachingAssignment().getClassGroup().getId().equals(classGroupId)).toList();
  if(matches.isEmpty())return List.of(); if(matches.size()>1)throw new BusinessRuleException("Plusieurs cours sont planifiés pour cette classe et ce créneau."); var schedule=matches.get(0); var yearId=schedule.getTeachingAssignment().getSchoolYear().getId();
  var enrolled=enrollments.findActiveClass(yearId,classGroupId,EnrollmentStatus.ACTIVE); var session=sessions.findByScheduleEntryIdAndSessionDate(schedule.getId(),date).orElse(null); Map<Long,StudentAttendance> byStudent=session==null?Map.of():attendances.findByClassSessionId(session.getId()).stream().collect(Collectors.toMap(x->x.getStudent().getId(),x->x));
  return enrolled.stream().map(e->{var st=e.getStudent();var p=st.getPerson();var a=byStudent.get(st.getId());var ta=schedule.getTeachingAssignment();var tp=ta.getTeacher().getEmployee().getPerson();return new ExpectedStudentAttendanceResponse(session==null?null:session.getId(),schedule.getId(),date,schedule.getTimeSlot().getId(),schedule.getTimeSlot().getCode(),schedule.getTimeSlot().getStartTime(),schedule.getTimeSlot().getEndTime(),classGroupId,ta.getClassGroup().getName(),ta.getSubject().getId(),ta.getSubject().getName(),ta.getTeacher().getId(),tp.getFirstName()+" "+tp.getLastName(),st.getId(),st.getStudentNumber(),p.getFirstName()+" "+p.getLastName(),a==null?null:a.getId(),a==null?null:a.getAttendanceStatus(),a==null?null:a.getLateMinutes(),a==null?null:a.getReason(),a!=null&&a.isJustified(),a==null?null:a.getNotes());}).toList();
 }
 public List<StudentAttendanceResponse> saveBatch(StudentAttendanceBatchRequest req){var current=currentUser();var schedule=getExpected(req.scheduleEntryId(),req.date());var session=getOrCreate(schedule,req.date());var yearId=schedule.getTeachingAssignment().getSchoolYear().getId();var classId=schedule.getTeachingAssignment().getClassGroup().getId();var allowed=enrollments.findActiveClass(yearId,classId,EnrollmentStatus.ACTIVE).stream().map(e->e.getStudent().getId()).collect(Collectors.toSet()); Set<Long> seen=new HashSet<>(); List<StudentAttendanceResponse> out=new ArrayList<>();
  for(var item:req.attendances()){if(!seen.add(item.studentId()))throw new BusinessRuleException("Le même élève apparaît plusieurs fois dans la saisie.");if(!allowed.contains(item.studentId()))throw new BusinessRuleException("Cet élève n'est pas inscrit activement dans cette classe pour l'année scolaire du cours.");if(item.status()==StudentAttendanceStatus.RETARD&&(item.lateMinutes()==null||item.lateMinutes()<=0))throw new BusinessRuleException("Le nombre de minutes de retard est obligatoire et doit être supérieur à zéro.");var student=enrollments.findByStudentIdAndSchoolYearId(item.studentId(),yearId).orElseThrow(()->new ResourceNotFoundException("Inscription élève introuvable")).getStudent();var a=attendances.findByClassSessionIdAndStudentId(session.getId(),student.getId()).orElseGet(StudentAttendance::new);var previousStatus=a.getId()==null?null:a.getAttendanceStatus();a.setClassSession(session);a.setStudent(student);a.setAttendanceStatus(item.status());a.setLateMinutes(item.status()==StudentAttendanceStatus.RETARD?item.lateMinutes():0);a.setReason(blank(item.reason()));a.setJustified(item.justified());a.setNotes(blank(item.notes()));a.setRecordedBy(current);a.setRecordedAt(OffsetDateTime.now());a.setValidatedBy(current);a.setValidatedAt(OffsetDateTime.now());a=attendances.save(a);if((item.status()==StudentAttendanceStatus.ABSENT||item.status()==StudentAttendanceStatus.RETARD)&&previousStatus!=item.status())attendanceEmailService.studentIncident(a);out.add(map(a));}return out; }
 @Transactional(readOnly=true) public PageResponse<StudentAttendanceResponse> history(LocalDate from,LocalDate to,Long studentId,Long classId,StudentAttendanceStatus status,Boolean justified,int page,int size){var pageable=PageRequest.of(Math.max(0,page),Math.min(100,Math.max(1,size)),Sort.by(Sort.Direction.DESC,"classSession.sessionDate").and(Sort.by("id").descending()));var result=attendances.findAll(spec(from,to,studentId,classId,status,justified),pageable).map(this::map);return PageResponse.from(result);}
 @Transactional(readOnly=true) public StudentAttendanceSummaryResponse summary(LocalDate from,LocalDate to,Long studentId,Long classId){var list=attendances.findAll(spec(from,to,studentId,classId,null,null));return new StudentAttendanceSummaryResponse(list.size(),list.stream().filter(a->a.getAttendanceStatus()==StudentAttendanceStatus.PRESENT).count(),list.stream().filter(a->a.getAttendanceStatus()==StudentAttendanceStatus.ABSENT).count(),list.stream().filter(a->a.getAttendanceStatus()==StudentAttendanceStatus.RETARD).count(),list.stream().filter(a->a.getAttendanceStatus()==StudentAttendanceStatus.ABSENT&&a.isJustified()).count(),list.stream().mapToLong(a->a.getLateMinutes()==null?0:a.getLateMinutes()).sum());}
 private Specification<StudentAttendance> spec(LocalDate f,LocalDate t,Long sid,Long cid,StudentAttendanceStatus st,Boolean just){return(root,q,cb)->{var ps=new ArrayList<jakarta.persistence.criteria.Predicate>();var s=root.join("classSession");if(f!=null)ps.add(cb.greaterThanOrEqualTo(s.get("sessionDate"),f));if(t!=null)ps.add(cb.lessThanOrEqualTo(s.get("sessionDate"),t));if(sid!=null)ps.add(cb.equal(root.get("student").get("id"),sid));if(cid!=null)ps.add(cb.equal(s.get("classGroup").get("id"),cid));if(st!=null)ps.add(cb.equal(root.get("attendanceStatus"),st));if(just!=null)ps.add(cb.equal(root.get("justified"),just));return cb.and(ps.toArray(new jakarta.persistence.criteria.Predicate[0]));};}
 private ScheduleEntry getExpected(Long id,LocalDate date){var s=schedules.findById(id).orElseThrow(()->new ResourceNotFoundException("Cours planifié introuvable"));var day=toSchoolDay(date.getDayOfWeek());if(s.getStatus()!=ScheduleEntryStatus.ACTIVE||day==null||s.getDayOfWeek()!=day||date.isBefore(s.getValidFrom())||(s.getValidUntil()!=null&&date.isAfter(s.getValidUntil())))throw new BusinessRuleException("Ce cours n'est pas prévu à cette date.");return s;}
 private ClassSession getOrCreate(ScheduleEntry s,LocalDate date){return sessions.findByScheduleEntryIdAndSessionDate(s.getId(),date).orElseGet(()->{var a=s.getTeachingAssignment();var x=new ClassSession();x.setScheduleEntry(s);x.setSessionDate(date);x.setTeacher(a.getTeacher());x.setClassGroup(a.getClassGroup());x.setSubject(a.getSubject());x.setTimeSlot(s.getTimeSlot());x.setRoom(s.getRoom());x.setStatus(ClassSessionStatus.PLANNED);x.setGeneratedFromSchedule(true);return sessions.save(x);});}
 private StudentAttendanceResponse map(StudentAttendance a){var s=a.getClassSession();var st=a.getStudent();var p=st.getPerson();return new StudentAttendanceResponse(a.getId(),s.getId(),s.getSessionDate(),s.getTimeSlot().getId(),s.getTimeSlot().getCode(),s.getClassGroup().getId(),s.getClassGroup().getName(),s.getSubject().getId(),s.getSubject().getName(),st.getId(),st.getStudentNumber(),p.getFirstName()+" "+p.getLastName(),a.getAttendanceStatus(),a.getLateMinutes(),a.getReason(),a.isJustified(),a.getNotes(),a.getRecordedAt(),a.getValidatedAt());}
 private UserAccount currentUser(){var x=SecurityContextHolder.getContext().getAuthentication();if(x==null||x.getName()==null)throw new BusinessRuleException("Utilisateur courant introuvable");return users.findByUsername(x.getName()).orElseThrow(()->new BusinessRuleException("Utilisateur courant introuvable"));} private String blank(String s){return s==null||s.isBlank()?null:s.trim();}
 private SchoolDay toSchoolDay(DayOfWeek d){return switch(d){case SUNDAY->SchoolDay.SUNDAY;case MONDAY->SchoolDay.MONDAY;case TUESDAY->SchoolDay.TUESDAY;case WEDNESDAY->SchoolDay.WEDNESDAY;case THURSDAY->SchoolDay.THURSDAY;default->null;};}
}
