spring:
  application:
    name: gestion-scolaire

  datasource:
    url: jdbc:postgresql://localhost:5433/gestion_scolaire_sls
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    clean-disabled: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:sls.school2008@gmail.com}
    password: ${MAIL_PASSWORD:enoi rylu czqq hdch}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false


app:
  bootstrap-admin:
    enabled: ${APP_BOOTSTRAP_ADMIN_ENABLED:false}
    username: ${APP_BOOTSTRAP_ADMIN_USERNAME:}
    password: ${APP_BOOTSTRAP_ADMIN_PASSWORD:}
    first-name: ${APP_BOOTSTRAP_ADMIN_FIRST_NAME:}
    last-name: ${APP_BOOTSTRAP_ADMIN_LAST_NAME:}
    email: ${APP_BOOTSTRAP_ADMIN_EMAIL:}

  security:
    login:
      max-failed-attempts: 5
      lock-duration-minutes: 15

  finance-email:
    enabled: ${APP_FINANCE_EMAIL_ENABLED:true}
    from: ${APP_FINANCE_EMAIL_FROM:sls.school2008@gmail.com}
    from-name: ${APP_FINANCE_EMAIL_FROM_NAME:Groupe Scolaire Sciences et Lettres}
    dispatcher:
      initial-delay-ms: 5000
      fixed-delay-ms: 30000

server:
  port: 8080

  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
