package com.ecole.gestion_scolaire.registration.entity;
import com.ecole.gestion_scolaire.registration.enums.*; import com.ecole.gestion_scolaire.student.entity.Student; import jakarta.persistence.*; import java.time.*;
@Entity @Table(name="student_enrollment",uniqueConstraints=@UniqueConstraint(name="uq_student_enrollment_student_id_school_year_id",columnNames={"student_id","school_year_id"}))
public class StudentEnrollment {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="student_id",nullable=false) private Student student;
 @Column(name="school_year_id",nullable=false) private Long schoolYearId; @Column(name="current_class_group_id",nullable=false) private Long currentClassGroupId; @Column(name="enrollment_date",nullable=false) private LocalDate enrollmentDate;
 @Enumerated(EnumType.STRING) @Column(name="entry_type",nullable=false,length=30) private EnrollmentEntryType entryType; @Enumerated(EnumType.STRING) @Column(nullable=false,length=30) private EnrollmentStatus status;
 @Column(name="exit_date") private LocalDate exitDate; @Column(name="exit_reason",columnDefinition="text") private String exitReason; @Column(name="created_at",nullable=false) private OffsetDateTime createdAt; @Column(name="updated_at",nullable=false) private OffsetDateTime updatedAt;
 @PrePersist void pre(){var n=OffsetDateTime.now(); if(createdAt==null)createdAt=n;updatedAt=n;if(enrollmentDate==null)enrollmentDate=LocalDate.now();if(status==null)status=EnrollmentStatus.ACTIVE;} @PreUpdate void upd(){updatedAt=OffsetDateTime.now();}
 public Long getId(){return id;} public Student getStudent(){return student;} public void setStudent(Student v){student=v;} public Long getSchoolYearId(){return schoolYearId;} public void setSchoolYearId(Long v){schoolYearId=v;} public Long getCurrentClassGroupId(){return currentClassGroupId;} public void setCurrentClassGroupId(Long v){currentClassGroupId=v;}
 public LocalDate getEnrollmentDate(){return enrollmentDate;} public void setEnrollmentDate(LocalDate v){enrollmentDate=v;} public EnrollmentEntryType getEntryType(){return entryType;} public void setEntryType(EnrollmentEntryType v){entryType=v;} public EnrollmentStatus getStatus(){return status;} public void setStatus(EnrollmentStatus v){status=v;} public LocalDate getExitDate(){return exitDate;} public void setExitDate(LocalDate v){exitDate=v;} public String getExitReason(){return exitReason;} public void setExitReason(String v){exitReason=v;} public OffsetDateTime getCreatedAt(){return createdAt;} public OffsetDateTime getUpdatedAt(){return updatedAt;}
}
