-- Compléments Finance V1 : suivi financier, échéanciers et consommation des avoirs.
-- V1 à V10 restent immuables.

CREATE TABLE family_credit_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_credit_id BIGINT NOT NULL REFERENCES family_credit(id) ON DELETE RESTRICT,
    guardian_id BIGINT NOT NULL REFERENCES guardian(id) ON DELETE RESTRICT,
    student_charge_id BIGINT NOT NULL REFERENCES student_charge(id) ON DELETE RESTRICT,
    payment_allocation_id BIGINT NOT NULL REFERENCES payment_allocation(id) ON DELETE RESTRICT,
    amount NUMERIC(14,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_family_credit_usage_amount_positive CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_student_charge_enrollment_due ON student_charge(student_enrollment_id, due_date);
CREATE INDEX IF NOT EXISTS idx_student_charge_registration_due ON student_charge(registration_case_id, due_date);
CREATE INDEX IF NOT EXISTS idx_student_charge_status_due ON student_charge(status, due_date);
CREATE INDEX IF NOT EXISTS idx_payment_guardian_date ON payment(guardian_id, payment_date);
CREATE INDEX IF NOT EXISTS idx_cash_register_session_register_status ON cash_register_session(cash_register_id, status, opened_at DESC);
CREATE INDEX IF NOT EXISTS idx_family_credit_guardian_status ON family_credit(guardian_id, status);
CREATE INDEX IF NOT EXISTS idx_family_credit_usage_credit ON family_credit_usage(family_credit_id, created_at DESC);
