-- Finance V13 : réductions, règles familiales, traçabilité et contrôle de caisse.
-- V1 à V12 restent immuables.

ALTER TABLE discount_rule
    ADD COLUMN IF NOT EXISTS condition_type VARCHAR(40) NOT NULL DEFAULT 'ALWAYS',
    ADD COLUMN IF NOT EXISTS child_rank INTEGER,
    ADD COLUMN IF NOT EXISTS cycle_id BIGINT REFERENCES cycle(id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS level_id BIGINT REFERENCES level(id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS class_group_id BIGINT REFERENCES class_group(id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS campus_id BIGINT REFERENCES campus(id) ON DELETE RESTRICT;

ALTER TABLE student_discount
    ADD COLUMN IF NOT EXISTS rejected_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS rejection_reason TEXT,
    ADD COLUMN IF NOT EXISTS applied_at TIMESTAMPTZ;

ALTER TABLE family_credit
    ALTER COLUMN source_payment_id DROP NOT NULL;

ALTER TABLE family_credit
    ADD COLUMN IF NOT EXISTS source_student_discount_id BIGINT
    REFERENCES student_discount(id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS source_type VARCHAR(30)
        NOT NULL DEFAULT 'PAYMENT';

ALTER TABLE family_credit_usage
    ALTER COLUMN payment_allocation_id DROP NOT NULL;


CREATE TABLE IF NOT EXISTS student_discount_adjustment (
                                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                                           student_discount_id BIGINT
                                                           REFERENCES student_discount(id) ON DELETE RESTRICT,

    discount_rule_id BIGINT
    REFERENCES discount_rule(id) ON DELETE RESTRICT,

    student_charge_id BIGINT NOT NULL
    REFERENCES student_charge(id) ON DELETE RESTRICT,

    previous_discount_amount NUMERIC(14,2) NOT NULL,
    new_discount_amount NUMERIC(14,2) NOT NULL,

    previous_final_amount NUMERIC(14,2) NOT NULL,
    new_final_amount NUMERIC(14,2) NOT NULL,

    credit_created NUMERIC(14,2) NOT NULL DEFAULT 0,

    applied_by BIGINT NOT NULL
    REFERENCES user_account(id) ON DELETE RESTRICT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_discount_adjustment_amounts CHECK (
    previous_discount_amount >= 0
    AND new_discount_amount >= 0
    AND previous_final_amount >= 0
    AND new_final_amount >= 0
    AND credit_created >= 0
                                                    )
    );


CREATE INDEX IF NOT EXISTS idx_discount_rule_scope
    ON discount_rule(
    school_year_id,
    fee_type_id,
    active
    );

CREATE INDEX IF NOT EXISTS idx_student_discount_status
    ON student_discount(
    student_enrollment_id,
    status
    );

CREATE INDEX IF NOT EXISTS idx_discount_adjustment_charge
    ON student_discount_adjustment(
    student_charge_id,
    created_at DESC
    );

CREATE INDEX IF NOT EXISTS idx_family_credit_source_discount
    ON family_credit(
    source_student_discount_id
    );


-- =========================================================
-- PERMISSIONS REDUCTIONS
-- =========================================================

INSERT INTO permission (
    code,
    name,
    module,
    description,
    active
)
VALUES
    (
        'REDUCTION_CONSULTER',
        'Consulter les réductions',
        'FINANCE',
        'Consulter les demandes, règles et réductions appliquées.',
        TRUE
    ),
    (
        'REDUCTION_CREER',
        'Créer une réduction',
        'FINANCE',
        'Créer une demande de réduction pour un élève.',
        TRUE
    ),
    (
        'REDUCTION_VALIDER',
        'Valider une réduction',
        'FINANCE',
        'Valider et appliquer une réduction financière.',
        TRUE
    ),
    (
        'REDUCTION_REFUSER',
        'Refuser une réduction',
        'FINANCE',
        'Refuser une demande de réduction.',
        TRUE
    ),
    (
        'REDUCTION_PARAMETRER',
        'Paramétrer les règles de réduction',
        'FINANCE',
        'Créer et modifier les règles automatiques de réduction.',
        TRUE
    )
    ON CONFLICT (code) DO NOTHING;


-- =========================================================
-- ADMIN : tous les droits réduction
-- =========================================================

INSERT INTO role_permission (
    role_id,
    permission_id
)
SELECT
    r.id,
    p.id
FROM role r
         CROSS JOIN permission p
WHERE r.code = 'ADMIN'
  AND p.code IN (
                 'REDUCTION_CONSULTER',
                 'REDUCTION_CREER',
                 'REDUCTION_VALIDER',
                 'REDUCTION_REFUSER',
                 'REDUCTION_PARAMETRER'
    )
    ON CONFLICT DO NOTHING;


-- =========================================================
-- COMPTABLE : consultation + création des demandes
-- =========================================================

INSERT INTO role_permission (
    role_id,
    permission_id
)
SELECT
    r.id,
    p.id
FROM role r
         CROSS JOIN permission p
WHERE r.code = 'COMPTABLE'
  AND p.code IN (
                 'REDUCTION_CONSULTER',
                 'REDUCTION_CREER'
    )
    ON CONFLICT DO NOTHING;