-- Finance V14 : contrepassation réelle des remboursements + outbox e-mail finance.
-- V1 à V13 restent immuables.

CREATE TABLE refund_allocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id BIGINT NOT NULL REFERENCES refund(id) ON DELETE RESTRICT,
    payment_allocation_id BIGINT NOT NULL REFERENCES payment_allocation(id) ON DELETE RESTRICT,
    student_charge_id BIGINT NOT NULL REFERENCES student_charge(id) ON DELETE RESTRICT,
    amount NUMERIC(14,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_refund_allocation_amount_positive CHECK (amount > 0)
);

CREATE INDEX idx_refund_allocation_refund ON refund_allocation(refund_id, id);
CREATE INDEX idx_refund_allocation_payment_allocation ON refund_allocation(payment_allocation_id);
CREATE INDEX idx_refund_allocation_charge ON refund_allocation(student_charge_id);

CREATE TABLE refund_credit_reversal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id BIGINT NOT NULL REFERENCES refund(id) ON DELETE RESTRICT,
    family_credit_id BIGINT NOT NULL REFERENCES family_credit(id) ON DELETE RESTRICT,
    amount NUMERIC(14,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_refund_credit_reversal_amount_positive CHECK (amount > 0)
);

CREATE INDEX idx_refund_credit_reversal_refund ON refund_credit_reversal(refund_id, id);
CREATE INDEX idx_refund_credit_reversal_credit ON refund_credit_reversal(family_credit_id);

CREATE TABLE finance_email_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_email VARCHAR(320) NOT NULL,
    subject VARCHAR(250) NOT NULL,
    body_html TEXT NOT NULL,
    document_type VARCHAR(40) NOT NULL,
    document_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMPTZ,
    CONSTRAINT ck_finance_email_attempt_count CHECK (attempt_count >= 0)
);

CREATE INDEX idx_finance_email_outbox_status_created ON finance_email_outbox(status, created_at);
CREATE INDEX idx_finance_email_outbox_document ON finance_email_outbox(document_type, document_id);
