-- Module Personnel / Enseignants. Ne modifie aucune migration V1-V14.
CREATE SEQUENCE IF NOT EXISTS employee_number_seq START WITH 1 INCREMENT BY 1;
CREATE INDEX IF NOT EXISTS idx_employee_person ON employee(person_id);
CREATE INDEX IF NOT EXISTS idx_employee_campus_status ON employee(campus_id, employment_status);
CREATE INDEX IF NOT EXISTS idx_teacher_employee ON teacher(employee_id);
CREATE INDEX IF NOT EXISTS idx_teaching_assignment_teacher_year ON teaching_assignment(teacher_id, school_year_id);
CREATE INDEX IF NOT EXISTS idx_teaching_assignment_class_year ON teaching_assignment(class_group_id, school_year_id);
CREATE INDEX IF NOT EXISTS idx_teacher_rate_teacher_year ON teacher_rate(teacher_id, school_year_id);
CREATE INDEX IF NOT EXISTS idx_compensation_plan_employee_year ON compensation_plan(employee_id, school_year_id);

CREATE TABLE IF NOT EXISTS employee_emergency_contact ( id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT, name VARCHAR(150) NOT NULL, relationship VARCHAR(80), phone VARCHAR(30) NOT NULL, secondary_phone VARCHAR(30), primary_contact BOOLEAN NOT NULL DEFAULT FALSE );
CREATE TABLE IF NOT EXISTS employee_admin_document ( id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT, document_type VARCHAR(80) NOT NULL, document_number VARCHAR(100), issued_on DATE, expires_on DATE, file_reference VARCHAR(500), status VARCHAR(30) NOT NULL, notes TEXT );
CREATE TABLE IF NOT EXISTS staff_note ( id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT, category VARCHAR(80) NOT NULL, content TEXT NOT NULL, created_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT, created_at TIMESTAMPTZ NOT NULL );

INSERT INTO permission (code,name,module,description,active) SELECT v.code,v.name,'PERSONNEL',v.description,TRUE FROM (VALUES
('PERSONNEL_CONSULTER','Consulter le personnel','Consulter les dossiers du personnel'),
('PERSONNEL_CREER','Créer un employé','Créer un dossier employé'),
('PERSONNEL_MODIFIER','Modifier un employé','Modifier les informations RH'),
('PERSONNEL_NOTES_GERER','Gérer les notes RH','Gérer les observations administratives sensibles'),
('PERSONNEL_DASHBOARD','Tableau de bord RH','Consulter les indicateurs personnel et enseignants'),
('ENSEIGNANT_CONSULTER','Consulter les enseignants','Consulter les enseignants et leurs matières'),
('ENSEIGNANT_CREER','Créer un enseignant','Créer le profil enseignant depuis un employé'),
('ENSEIGNANT_MODIFIER','Modifier un enseignant','Modifier le statut enseignant'),
('ENSEIGNANT_AFFECTER','Affecter un enseignant','Gérer matières, classes et affectations pédagogiques'),
('REMUNERATION_CONSULTER','Consulter la rémunération','Consulter plans et tarifs enseignants'),
('REMUNERATION_GERER','Gérer la rémunération','Créer plans mensuels, horaires ou mixtes et grilles tarifaires')
) AS v(code,name,description) WHERE NOT EXISTS (SELECT 1 FROM permission p WHERE p.code=v.code);

INSERT INTO role_permission(role_id,permission_id) SELECT r.id,p.id FROM role r CROSS JOIN permission p WHERE r.code='ADMIN' AND p.module='PERSONNEL' AND NOT EXISTS (SELECT 1 FROM role_permission rp WHERE rp.role_id=r.id AND rp.permission_id=p.id);
INSERT INTO role_permission(role_id,permission_id) SELECT r.id,p.id FROM role r CROSS JOIN permission p WHERE r.code='DIRECTEUR_PEDAGOGIQUE' AND p.code IN ('PERSONNEL_CONSULTER','PERSONNEL_DASHBOARD','ENSEIGNANT_CONSULTER','ENSEIGNANT_AFFECTER','REMUNERATION_CONSULTER') AND NOT EXISTS (SELECT 1 FROM role_permission rp WHERE rp.role_id=r.id AND rp.permission_id=p.id);
