-- V16 - Référentiels RH : matières administrables et postes/fonctions.
-- IMPORTANT : ne modifie aucune migration V1 à V15.

CREATE TABLE IF NOT EXISTS job_position (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) NOT NULL,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(60),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_job_position_code_ci
    ON job_position (LOWER(code));
CREATE UNIQUE INDEX IF NOT EXISTS uq_job_position_name_ci
    ON job_position (LOWER(name));
CREATE INDEX IF NOT EXISTS idx_job_position_active_order
    ON job_position (active, display_order, name);

-- Référentiel initial. Il reste administrable via l'API /api/hr/job-positions.
INSERT INTO job_position(code, name, category, active, display_order)
SELECT v.code, v.name, v.category, TRUE, v.display_order
FROM (VALUES
    ('ENSEIGNANT', 'Enseignant', 'PEDAGOGIQUE', 10),
    ('DIRECTEUR_GENERAL', 'Directeur général', 'DIRECTION', 20),
    ('DIRECTEUR_PEDAGOGIQUE', 'Directeur pédagogique', 'DIRECTION', 30),
    ('DIRECTEUR_FINANCIER', 'Directeur financier', 'DIRECTION', 40),
    ('SURVEILLANT_GENERAL', 'Surveillant général', 'VIE_SCOLAIRE', 50),
    ('SURVEILLANT_PRIMAIRE', 'Surveillant primaire', 'VIE_SCOLAIRE', 60),
    ('SURVEILLANT_COLLEGE', 'Surveillant collège', 'VIE_SCOLAIRE', 70),
    ('SURVEILLANT_LYCEE', 'Surveillant lycée', 'VIE_SCOLAIRE', 80),
    ('COMPTABLE', 'Comptable', 'FINANCE', 90),
    ('ASSISTANTE_ADMINISTRATIVE', 'Assistante administrative', 'ADMINISTRATIF', 100),
    ('SECRETAIRE', 'Secrétaire', 'ADMINISTRATIF', 110),
    ('AGENT_ADMINISTRATIF', 'Agent administratif', 'ADMINISTRATIF', 120),
    ('RESPONSABLE_RH', 'Responsable ressources humaines', 'RH', 130),
    ('RESPONSABLE_TRANSPORT', 'Responsable transport', 'TRANSPORT', 140),
    ('CHAUFFEUR', 'Chauffeur', 'TRANSPORT', 150),
    ('BIBLIOTHECAIRE', 'Bibliothécaire', 'PEDAGOGIQUE', 160),
    ('CONSEILLER_ORIENTATION', 'Conseiller d''orientation', 'PEDAGOGIQUE', 170),
    ('INFIRMIER_SCOLAIRE', 'Infirmier scolaire', 'SANTE', 180),
    ('RESPONSABLE_INFORMATIQUE', 'Responsable informatique', 'TECHNIQUE', 190),
    ('TECHNICIEN_INFORMATIQUE', 'Technicien informatique', 'TECHNIQUE', 200),
    ('AGENT_SECURITE', 'Agent de sécurité', 'SERVICES', 210),
    ('AGENT_ENTRETIEN', 'Agent d''entretien', 'SERVICES', 220),
    ('CUISINIER', 'Cuisinier', 'RESTAURATION', 230),
    ('AGENT_RESTAURATION', 'Agent de restauration', 'RESTAURATION', 240),
    ('AUTRE', 'Autre', 'AUTRE', 999)
) AS v(code, name, category, display_order)
WHERE NOT EXISTS (
    SELECT 1 FROM job_position jp
    WHERE LOWER(jp.code) = LOWER(v.code) OR LOWER(jp.name) = LOWER(v.name)
);

-- Reprise des éventuels intitulés déjà présents avant V16 afin de ne perdre aucune donnée.
INSERT INTO job_position(code, name, category, active, display_order)
SELECT
    'LEGACY_' || UPPER(SUBSTRING(MD5(TRIM(e.position_title)) FROM 1 FOR 12)),
    TRIM(e.position_title),
    'AUTRE',
    TRUE,
    900
FROM employee e
WHERE e.position_title IS NOT NULL
  AND TRIM(e.position_title) <> ''
  AND NOT EXISTS (
      SELECT 1 FROM job_position jp
      WHERE LOWER(TRIM(jp.name)) = LOWER(TRIM(e.position_title))
  )
GROUP BY TRIM(e.position_title)
ON CONFLICT DO NOTHING;

ALTER TABLE employee
    ADD COLUMN IF NOT EXISTS position_id BIGINT;

UPDATE employee e
SET position_id = jp.id
FROM job_position jp
WHERE e.position_id IS NULL
  AND LOWER(TRIM(jp.name)) = LOWER(TRIM(e.position_title));

-- Sécurité pour d'éventuelles anciennes lignes avec un intitulé vide ou atypique.
UPDATE employee e
SET position_id = jp.id,
    position_title = CASE WHEN TRIM(COALESCE(e.position_title, '')) = '' THEN jp.name ELSE e.position_title END
FROM job_position jp
WHERE e.position_id IS NULL
  AND jp.code = 'AUTRE';

ALTER TABLE employee
    DROP CONSTRAINT IF EXISTS fk_employee_job_position;
ALTER TABLE employee
    ADD CONSTRAINT fk_employee_job_position
    FOREIGN KEY (position_id) REFERENCES job_position(id) ON DELETE RESTRICT;

-- Toute ligne employee historique possédait déjà position_title NOT NULL : le backfill ci-dessus
-- permet donc de rendre le référentiel obligatoire sans casser les données existantes.
ALTER TABLE employee
    ALTER COLUMN position_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_employee_position ON employee(position_id);

-- Matières de départ. Elles sont elles aussi entièrement administrables.
INSERT INTO subject(code, name, active, display_order)
SELECT v.code, v.name, TRUE, v.display_order
FROM (VALUES
    ('AR', 'Arabe', 10),
    ('FR', 'Français', 20),
    ('EN', 'Anglais', 30),
    ('ES', 'Espagnol', 40),
    ('MATH', 'Mathématiques', 50),
    ('INFO', 'Informatique', 60),
    ('SCI', 'Sciences', 70),
    ('SVT', 'Sciences naturelles', 80),
    ('PHY', 'Physique', 90),
    ('CHIM', 'Chimie', 100),
    ('HG', 'Histoire-Géographie', 110),
    ('CIV', 'Éducation civique', 120),
    ('ISL', 'Éducation islamique', 130),
    ('PHILO', 'Philosophie', 140),
    ('TECH', 'Technologie', 150),
    ('EPS', 'Éducation physique et sportive', 160),
    ('ART', 'Dessin / Arts plastiques', 170),
    ('ECO', 'Économie', 180),
    ('GEST', 'Gestion', 190)
) AS v(code, name, display_order)
WHERE NOT EXISTS (
    SELECT 1 FROM subject s
    WHERE LOWER(s.code) = LOWER(v.code) OR LOWER(s.name) = LOWER(v.name)
);

-- Permissions des deux référentiels.
INSERT INTO permission(code, name, module, description, active)
SELECT v.code, v.name, 'PERSONNEL', v.description, TRUE
FROM (VALUES
    ('MATIERE_CONSULTER', 'Consulter les matières', 'Consulter le référentiel des matières'),
    ('MATIERE_GERER', 'Gérer les matières', 'Créer, modifier, activer ou désactiver une matière'),
    ('POSTE_CONSULTER', 'Consulter les postes', 'Consulter le référentiel des postes et fonctions'),
    ('POSTE_GERER', 'Gérer les postes', 'Créer, modifier, activer ou désactiver un poste ou une fonction')
) AS v(code, name, description)
WHERE NOT EXISTS (SELECT 1 FROM permission p WHERE p.code = v.code);

INSERT INTO role_permission(role_id, permission_id)
SELECT r.id, p.id
FROM role r
CROSS JOIN permission p
WHERE r.code = 'ADMIN'
  AND p.code IN ('MATIERE_CONSULTER','MATIERE_GERER','POSTE_CONSULTER','POSTE_GERER')
  AND NOT EXISTS (
      SELECT 1 FROM role_permission rp
      WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );

INSERT INTO role_permission(role_id, permission_id)
SELECT r.id, p.id
FROM role r
CROSS JOIN permission p
WHERE r.code = 'DIRECTEUR_PEDAGOGIQUE'
  AND p.code IN ('MATIERE_CONSULTER','MATIERE_GERER','POSTE_CONSULTER')
  AND NOT EXISTS (
      SELECT 1 FROM role_permission rp
      WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );
