-- V1__initial_schema.sql
-- Application de gestion scolaire - schema PostgreSQL initial
-- Source: Modele_final_donnees_application_gestion_scolaire.docx (06-09-2026)
-- PostgreSQL 15+ / Flyway

BEGIN;

CREATE TABLE application_setting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    value TEXT NOT NULL,
    value_type VARCHAR(30) NOT NULL,
    scope_type VARCHAR(30),
    scope_reference_id BIGINT,
    effective_from DATE,
    effective_until DATE,
    active BOOLEAN NOT NULL,
    description TEXT
);

CREATE TABLE assessment_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(120) NOT NULL,
    category VARCHAR(50),
    default_coefficient NUMERIC(6,2) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE campus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(150) NOT NULL,
    address VARCHAR(300),
    phone VARCHAR(30),
    active BOOLEAN NOT NULL
);

CREATE TABLE contribution_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) NOT NULL,
    name VARCHAR(150) NOT NULL,
    payer_type VARCHAR(20) NOT NULL,
    rate NUMERIC(10,6),
    base_type VARCHAR(40) NOT NULL,
    effective_from DATE NOT NULL,
    effective_until DATE,
    active BOOLEAN NOT NULL
);

CREATE TABLE cycle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    display_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE expense_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) NOT NULL,
    name VARCHAR(150) NOT NULL,
    parent_category_id BIGINT,
    active BOOLEAN NOT NULL
);

CREATE TABLE fee_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL,
    display_order INTEGER
);

CREATE TABLE leave_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(120) NOT NULL,
    paid BOOLEAN NOT NULL,
    requires_approval BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE payment_method (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    module VARCHAR(80) NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL
);

CREATE TABLE person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    birth_date DATE,
    birth_place VARCHAR(150),
    nationality VARCHAR(80),
    sex VARCHAR(20),
    address VARCHAR(300),
    phone VARCHAR(30),
    secondary_phone VARCHAR(30),
    email VARCHAR(150),
    photo_reference VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE provider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    tax_identifier VARCHAR(100),
    address VARCHAR(300),
    phone VARCHAR(30),
    email VARCHAR(150),
    contact_person VARCHAR(150),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE provider_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) NOT NULL,
    name VARCHAR(150) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE registration_document_requirement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(200) NOT NULL,
    applicable_to VARCHAR(50) NOT NULL,
    required BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    system_role BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE school_year (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL,
    label VARCHAR(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    current_year BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    active BOOLEAN NOT NULL,
    display_order INTEGER
);

CREATE TABLE time_slot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    display_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE transport_stop (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    address VARCHAR(300),
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code VARCHAR(60) NOT NULL,
    name VARCHAR(150) NOT NULL,
    asset_type VARCHAR(50) NOT NULL,
    campus_id BIGINT REFERENCES campus(id) ON DELETE RESTRICT,
    acquisition_date DATE,
    provider_id BIGINT REFERENCES provider(id) ON DELETE RESTRICT,
    purchase_price NUMERIC(14,2),
    serial_number VARCHAR(150),
    status VARCHAR(30) NOT NULL,
    notes TEXT
);

CREATE TABLE cash_register (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    campus_id BIGINT REFERENCES campus(id) ON DELETE RESTRICT,
    active BOOLEAN NOT NULL
);

CREATE TABLE discount_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year_id BIGINT NOT NULL REFERENCES school_year(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    discount_type VARCHAR(30) NOT NULL,
    value NUMERIC(14,2) NOT NULL,
    fee_type_id BIGINT REFERENCES fee_type(id) ON DELETE RESTRICT,
    priority INTEGER NOT NULL,
    requires_approval BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL,
    valid_from DATE,
    valid_until DATE
);

CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES person(id) ON DELETE RESTRICT,
    employee_number VARCHAR(50) NOT NULL,
    social_security_number VARCHAR(100),
    position_title VARCHAR(150) NOT NULL,
    campus_id BIGINT REFERENCES campus(id) ON DELETE RESTRICT,
    hire_date DATE,
    end_date DATE,
    employment_status VARCHAR(30) NOT NULL,
    marital_status VARCHAR(30),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE guardian (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES person(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE level (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT NOT NULL REFERENCES cycle(id) ON DELETE RESTRICT,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    display_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE payroll_parameter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year_id BIGINT REFERENCES school_year(id) ON DELETE RESTRICT,
    code VARCHAR(80) NOT NULL,
    value NUMERIC(18,6) NOT NULL,
    value_type VARCHAR(30) NOT NULL,
    effective_from DATE NOT NULL,
    effective_until DATE,
    description TEXT,
    active BOOLEAN NOT NULL
);

CREATE TABLE provider_category_assignment (
    provider_id BIGINT NOT NULL REFERENCES provider(id) ON DELETE RESTRICT,
    category_id BIGINT NOT NULL REFERENCES provider_category(id) ON DELETE RESTRICT,
    PRIMARY KEY (provider_id, category_id)
);

CREATE TABLE provider_contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES provider(id) ON DELETE RESTRICT,
    campus_id BIGINT REFERENCES campus(id) ON DELETE RESTRICT,
    contract_number VARCHAR(100),
    contract_type VARCHAR(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    amount NUMERIC(14,2),
    billing_frequency VARCHAR(30),
    status VARCHAR(30) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE recurring_expense (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT REFERENCES provider(id) ON DELETE RESTRICT,
    expense_category_id BIGINT NOT NULL REFERENCES expense_category(id) ON DELETE RESTRICT,
    campus_id BIGINT REFERENCES campus(id) ON DELETE RESTRICT,
    description VARCHAR(250) NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    frequency VARCHAR(30) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    next_generation_date DATE,
    active BOOLEAN NOT NULL
);

CREATE TABLE role_permission (
    role_id BIGINT NOT NULL REFERENCES role(id) ON DELETE RESTRICT,
    permission_id BIGINT NOT NULL REFERENCES permission(id) ON DELETE RESTRICT,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL REFERENCES campus(id) ON DELETE RESTRICT,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    capacity INTEGER,
    room_type VARCHAR(30),
    active BOOLEAN NOT NULL
);

CREATE TABLE school_calendar_exception (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year_id BIGINT NOT NULL REFERENCES school_year(id) ON DELETE RESTRICT,
    campus_id BIGINT REFERENCES campus(id) ON DELETE RESTRICT,
    cycle_id BIGINT REFERENCES cycle(id) ON DELETE RESTRICT,
    exception_date DATE NOT NULL,
    exception_type VARCHAR(40) NOT NULL,
    label VARCHAR(200) NOT NULL,
    description TEXT
);

CREATE TABLE student (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES person(id) ON DELETE RESTRICT,
    student_number VARCHAR(50) NOT NULL,
    initial_admission_date DATE,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE transport_route (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year_id BIGINT NOT NULL REFERENCES school_year(id) ON DELETE RESTRICT,
    campus_id BIGINT REFERENCES campus(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    route_type VARCHAR(30) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES person(id) ON DELETE RESTRICT,
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL,
    must_change_password BOOLEAN NOT NULL,
    failed_login_attempts INTEGER NOT NULL,
    locked_until TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE vehicle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number VARCHAR(50) NOT NULL,
    internal_code VARCHAR(50),
    brand VARCHAR(100),
    model VARCHAR(100),
    capacity INTEGER NOT NULL,
    vehicle_type VARCHAR(40),
    ownership_type VARCHAR(40) NOT NULL,
    provider_id BIGINT REFERENCES provider(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE academic_period (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year_id BIGINT NOT NULL REFERENCES school_year(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    period_type VARCHAR(30) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    display_order INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,
    locked_at TIMESTAMPTZ,
    locked_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(100),
    old_values JSONB,
    new_values JSONB,
    reason TEXT,
    ip_address VARCHAR(64),
    user_agent VARCHAR(500),
    occurred_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE authorized_pickup_person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    relationship VARCHAR(100),
    phone VARCHAR(30) NOT NULL,
    identity_document_number VARCHAR(100),
    issued_by VARCHAR(150),
    valid_from DATE,
    valid_until DATE,
    active BOOLEAN NOT NULL
);

CREATE TABLE cash_register_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_register_id BIGINT NOT NULL REFERENCES cash_register(id) ON DELETE RESTRICT,
    cashier_id BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    opened_at TIMESTAMPTZ NOT NULL,
    opening_balance NUMERIC(14,2) NOT NULL,
    closed_at TIMESTAMPTZ,
    expected_closing_balance NUMERIC(14,2),
    actual_closing_balance NUMERIC(14,2),
    difference_amount NUMERIC(14,2),
    status VARCHAR(30) NOT NULL,
    closed_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT
);

CREATE TABLE class_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year_id BIGINT NOT NULL REFERENCES school_year(id) ON DELETE RESTRICT,
    level_id BIGINT NOT NULL REFERENCES level(id) ON DELETE RESTRICT,
    campus_id BIGINT NOT NULL REFERENCES campus(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    capacity INTEGER,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE driver_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT,
    license_number VARCHAR(100) NOT NULL,
    license_category VARCHAR(50),
    license_expiry_date DATE,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE employee_leave (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT,
    leave_type_id BIGINT NOT NULL REFERENCES leave_type(id) ON DELETE RESTRICT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    duration_days NUMERIC(6,2),
    reason TEXT,
    status VARCHAR(30) NOT NULL,
    requested_at TIMESTAMPTZ NOT NULL,
    approved_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    approved_at TIMESTAMPTZ,
    notes TEXT
);

CREATE TABLE employee_medical_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT,
    blood_group VARCHAR(10),
    medical_conditions TEXT,
    allergies TEXT,
    notes TEXT,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE employee_qualification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT,
    qualification_type VARCHAR(50),
    title VARCHAR(200) NOT NULL,
    institution VARCHAR(200),
    specialty VARCHAR(150),
    obtained_date DATE,
    description TEXT
);

CREATE TABLE employment_contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT,
    contract_number VARCHAR(80),
    contract_type VARCHAR(40) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    position_title VARCHAR(150),
    workload_type VARCHAR(30),
    weekly_hours NUMERIC(6,2),
    status VARCHAR(30) NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE employment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT,
    institution_name VARCHAR(200) NOT NULL,
    position_title VARCHAR(150),
    start_date DATE,
    end_date DATE,
    description TEXT
);

CREATE TABLE internal_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_number VARCHAR(60) NOT NULL,
    requester_employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT,
    campus_id BIGINT REFERENCES campus(id) ON DELETE RESTRICT,
    department VARCHAR(100),
    request_date DATE NOT NULL,
    needed_by_date DATE,
    reason TEXT NOT NULL,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE level_subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year_id BIGINT NOT NULL REFERENCES school_year(id) ON DELETE RESTRICT,
    level_id BIGINT NOT NULL REFERENCES level(id) ON DELETE RESTRICT,
    subject_id BIGINT NOT NULL REFERENCES subject(id) ON DELETE RESTRICT,
    active BOOLEAN NOT NULL
);

CREATE TABLE maintenance_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT REFERENCES asset(id) ON DELETE RESTRICT,
    vehicle_id BIGINT REFERENCES vehicle(id) ON DELETE RESTRICT,
    campus_id BIGINT REFERENCES campus(id) ON DELETE RESTRICT,
    reported_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    reported_at TIMESTAMPTZ NOT NULL,
    problem_description TEXT NOT NULL,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    assigned_provider_id BIGINT REFERENCES provider(id) ON DELETE RESTRICT,
    resolved_at TIMESTAMPTZ,
    resolution_notes TEXT
);

CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    notification_type VARCHAR(60) NOT NULL,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    priority VARCHAR(20) NOT NULL,
    source_type VARCHAR(50),
    source_reference_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    read_at TIMESTAMPTZ
);

CREATE TABLE payroll_period (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year_id BIGINT REFERENCES school_year(id) ON DELETE RESTRICT,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    closed_at TIMESTAMPTZ,
    closed_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT
);

CREATE TABLE purchase_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(60) NOT NULL,
    provider_id BIGINT NOT NULL REFERENCES provider(id) ON DELETE RESTRICT,
    campus_id BIGINT REFERENCES campus(id) ON DELETE RESTRICT,
    order_date DATE NOT NULL,
    expected_delivery_date DATE,
    status VARCHAR(30) NOT NULL,
    subtotal NUMERIC(14,2) NOT NULL,
    discount_amount NUMERIC(14,2) NOT NULL,
    tax_amount NUMERIC(14,2) NOT NULL,
    total_amount NUMERIC(14,2) NOT NULL,
    created_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    approved_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE push_device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    device_token VARCHAR(500) NOT NULL,
    platform VARCHAR(30) NOT NULL,
    device_name VARCHAR(150),
    active BOOLEAN NOT NULL,
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE recurring_payroll_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT,
    item_type VARCHAR(40) NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    description VARCHAR(250),
    active BOOLEAN NOT NULL
);

CREATE TABLE route_stop (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL REFERENCES transport_route(id) ON DELETE RESTRICT,
    stop_id BIGINT NOT NULL REFERENCES transport_stop(id) ON DELETE RESTRICT,
    sequence_number INTEGER NOT NULL,
    planned_arrival_time TIME,
    planned_departure_time TIME,
    active BOOLEAN NOT NULL
);

CREATE TABLE student_family_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
    father_life_status VARCHAR(20),
    mother_life_status VARCHAR(20),
    parents_divorced BOOLEAN,
    number_of_brothers INTEGER,
    number_of_sisters INTEGER,
    notes TEXT,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE student_guardian (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
    guardian_id BIGINT NOT NULL REFERENCES guardian(id) ON DELETE RESTRICT,
    relationship_type VARCHAR(30) NOT NULL,
    legal_guardian BOOLEAN NOT NULL,
    financial_responsible BOOLEAN NOT NULL,
    primary_contact BOOLEAN NOT NULL,
    lives_with_student BOOLEAN,
    pickup_authorized BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL,
    valid_from DATE,
    valid_until DATE
);

CREATE TABLE student_medical_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
    blood_group VARCHAR(10),
    medical_conditions TEXT,
    allergies TEXT,
    treatments TEXT,
    emergency_notes TEXT,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE subject_coefficient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year_id BIGINT NOT NULL REFERENCES school_year(id) ON DELETE RESTRICT,
    level_id BIGINT NOT NULL REFERENCES level(id) ON DELETE RESTRICT,
    subject_id BIGINT NOT NULL REFERENCES subject(id) ON DELETE RESTRICT,
    coefficient NUMERIC(6,2) NOT NULL,
    effective_from DATE NOT NULL,
    effective_until DATE,
    active BOOLEAN NOT NULL
);

CREATE TABLE teacher (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE transport_staff_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT,
    route_id BIGINT NOT NULL REFERENCES transport_route(id) ON DELETE RESTRICT,
    role_type VARCHAR(30) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR(30) NOT NULL
);

CREATE TABLE user_role (
    user_account_id BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    role_id BIGINT NOT NULL REFERENCES role(id) ON DELETE RESTRICT,
    assigned_at TIMESTAMPTZ NOT NULL,
    assigned_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    PRIMARY KEY (user_account_id, role_id)
);

CREATE TABLE user_scope (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    scope_type VARCHAR(30) NOT NULL,
    scope_reference_id BIGINT NOT NULL,
    valid_from DATE,
    valid_until DATE,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE class_teacher_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year_id BIGINT NOT NULL REFERENCES school_year(id) ON DELETE RESTRICT,
    class_group_id BIGINT NOT NULL REFERENCES class_group(id) ON DELETE RESTRICT,
    teacher_id BIGINT NOT NULL REFERENCES teacher(id) ON DELETE RESTRICT,
    role_type VARCHAR(40) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE
);

CREATE TABLE compensation_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT,
    school_year_id BIGINT REFERENCES school_year(id) ON DELETE RESTRICT,
    employment_contract_id BIGINT REFERENCES employment_contract(id) ON DELETE RESTRICT,
    compensation_type VARCHAR(30) NOT NULL,
    monthly_salary NUMERIC(14,2),
    hourly_rate NUMERIC(14,2),
    fixed_part NUMERIC(14,2),
    expected_monthly_hours NUMERIC(8,2),
    effective_from DATE NOT NULL,
    effective_until DATE,
    status VARCHAR(30) NOT NULL,
    created_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE goods_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_order(id) ON DELETE RESTRICT,
    receipt_date DATE NOT NULL,
    received_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE internal_request_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internal_request_id BIGINT NOT NULL REFERENCES internal_request(id) ON DELETE RESTRICT,
    item_description VARCHAR(250) NOT NULL,
    quantity NUMERIC(12,3) NOT NULL,
    unit VARCHAR(30),
    estimated_unit_price NUMERIC(14,2),
    estimated_total NUMERIC(14,2),
    notes TEXT
);

CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_number VARCHAR(50) NOT NULL,
    guardian_id BIGINT NOT NULL REFERENCES guardian(id) ON DELETE RESTRICT,
    payment_date TIMESTAMPTZ NOT NULL,
    payment_method_id BIGINT NOT NULL REFERENCES payment_method(id) ON DELETE RESTRICT,
    total_amount NUMERIC(14,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    cashier_id BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    cash_register_session_id BIGINT REFERENCES cash_register_session(id) ON DELETE RESTRICT,
    external_reference VARCHAR(150),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    validated_at TIMESTAMPTZ,
    validated_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    cancelled_at TIMESTAMPTZ,
    cancelled_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    cancellation_reason TEXT
);

CREATE TABLE payroll_adjustment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT,
    payroll_period_id BIGINT NOT NULL REFERENCES payroll_period(id) ON DELETE RESTRICT,
    adjustment_type VARCHAR(40) NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    reason TEXT NOT NULL,
    source_type VARCHAR(50),
    source_reference_id BIGINT,
    status VARCHAR(30) NOT NULL,
    created_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    validated_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    validated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE provider_invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES provider(id) ON DELETE RESTRICT,
    invoice_number VARCHAR(100) NOT NULL,
    invoice_date DATE NOT NULL,
    due_date DATE,
    purchase_order_id BIGINT REFERENCES purchase_order(id) ON DELETE RESTRICT,
    campus_id BIGINT REFERENCES campus(id) ON DELETE RESTRICT,
    subtotal NUMERIC(14,2) NOT NULL,
    discount_amount NUMERIC(14,2) NOT NULL,
    tax_amount NUMERIC(14,2) NOT NULL,
    total_amount NUMERIC(14,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    reference VARCHAR(150),
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE provider_payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES provider(id) ON DELETE RESTRICT,
    payment_date TIMESTAMPTZ NOT NULL,
    payment_method_id BIGINT NOT NULL REFERENCES payment_method(id) ON DELETE RESTRICT,
    amount NUMERIC(14,2) NOT NULL,
    reference VARCHAR(150),
    status VARCHAR(30) NOT NULL,
    cash_register_session_id BIGINT REFERENCES cash_register_session(id) ON DELETE RESTRICT,
    paid_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL,
    cancelled_at TIMESTAMPTZ,
    cancelled_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    cancellation_reason TEXT
);

CREATE TABLE purchase_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_order(id) ON DELETE RESTRICT,
    description VARCHAR(250) NOT NULL,
    quantity NUMERIC(12,3) NOT NULL,
    unit VARCHAR(30),
    unit_price NUMERIC(14,2) NOT NULL,
    discount_amount NUMERIC(14,2) NOT NULL,
    tax_amount NUMERIC(14,2) NOT NULL,
    line_total NUMERIC(14,2) NOT NULL
);

CREATE TABLE purchase_order_request (
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_order(id) ON DELETE RESTRICT,
    internal_request_id BIGINT NOT NULL REFERENCES internal_request(id) ON DELETE RESTRICT,
    PRIMARY KEY (purchase_order_id, internal_request_id)
);

CREATE TABLE registration_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year_id BIGINT NOT NULL REFERENCES school_year(id) ON DELETE RESTRICT,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
    guardian_id BIGINT NOT NULL REFERENCES guardian(id) ON DELETE RESTRICT,
    requested_level_id BIGINT NOT NULL REFERENCES level(id) ON DELETE RESTRICT,
    requested_class_group_id BIGINT REFERENCES class_group(id) ON DELETE RESTRICT,
    registration_date DATE NOT NULL,
    status VARCHAR(40) NOT NULL,
    created_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    finalized_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    cancellation_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE request_approval (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internal_request_id BIGINT NOT NULL REFERENCES internal_request(id) ON DELETE RESTRICT,
    approval_step VARCHAR(50) NOT NULL,
    approver_id BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL,
    decision_at TIMESTAMPTZ,
    comment TEXT
);

CREATE TABLE route_vehicle_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL REFERENCES transport_route(id) ON DELETE RESTRICT,
    vehicle_id BIGINT NOT NULL REFERENCES vehicle(id) ON DELETE RESTRICT,
    driver_profile_id BIGINT NOT NULL REFERENCES driver_profile(id) ON DELETE RESTRICT,
    effective_from DATE NOT NULL,
    effective_until DATE,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE student_enrollment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
    school_year_id BIGINT NOT NULL REFERENCES school_year(id) ON DELETE RESTRICT,
    current_class_group_id BIGINT NOT NULL REFERENCES class_group(id) ON DELETE RESTRICT,
    enrollment_date DATE NOT NULL,
    entry_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    exit_date DATE,
    exit_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE student_exit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
    school_year_id BIGINT NOT NULL REFERENCES school_year(id) ON DELETE RESTRICT,
    exit_date DATE NOT NULL,
    exit_time TIME NOT NULL,
    reason TEXT,
    pickup_person_id BIGINT REFERENCES authorized_pickup_person(id) ON DELETE RESTRICT,
    guardian_authorization BOOLEAN NOT NULL,
    authorized_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    recorded_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE tariff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year_id BIGINT NOT NULL REFERENCES school_year(id) ON DELETE RESTRICT,
    fee_type_id BIGINT NOT NULL REFERENCES fee_type(id) ON DELETE RESTRICT,
    level_id BIGINT REFERENCES level(id) ON DELETE RESTRICT,
    class_group_id BIGINT REFERENCES class_group(id) ON DELETE RESTRICT,
    campus_id BIGINT REFERENCES campus(id) ON DELETE RESTRICT,
    amount NUMERIC(14,2) NOT NULL,
    billing_frequency VARCHAR(30) NOT NULL,
    valid_from DATE NOT NULL,
    valid_until DATE,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE teacher_rate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT NOT NULL REFERENCES teacher(id) ON DELETE RESTRICT,
    school_year_id BIGINT NOT NULL REFERENCES school_year(id) ON DELETE RESTRICT,
    class_group_id BIGINT REFERENCES class_group(id) ON DELETE RESTRICT,
    subject_id BIGINT REFERENCES subject(id) ON DELETE RESTRICT,
    work_type VARCHAR(40) NOT NULL,
    hourly_rate NUMERIC(14,2) NOT NULL,
    effective_from DATE NOT NULL,
    effective_until DATE,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE teacher_subject (
    teacher_id BIGINT NOT NULL REFERENCES teacher(id) ON DELETE RESTRICT,
    subject_id BIGINT NOT NULL REFERENCES subject(id) ON DELETE RESTRICT,
    PRIMARY KEY (teacher_id, subject_id)
);

CREATE TABLE teaching_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year_id BIGINT NOT NULL REFERENCES school_year(id) ON DELETE RESTRICT,
    teacher_id BIGINT NOT NULL REFERENCES teacher(id) ON DELETE RESTRICT,
    subject_id BIGINT NOT NULL REFERENCES subject(id) ON DELETE RESTRICT,
    class_group_id BIGINT NOT NULL REFERENCES class_group(id) ON DELETE RESTRICT,
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE transport_trip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL REFERENCES transport_route(id) ON DELETE RESTRICT,
    vehicle_id BIGINT NOT NULL REFERENCES vehicle(id) ON DELETE RESTRICT,
    driver_profile_id BIGINT NOT NULL REFERENCES driver_profile(id) ON DELETE RESTRICT,
    trip_date DATE NOT NULL,
    direction VARCHAR(30) NOT NULL,
    status VARCHAR(40) NOT NULL,
    planned_start_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    arrived_at_school_at TIMESTAMPTZ,
    return_started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE annual_student_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_enrollment_id BIGINT NOT NULL REFERENCES student_enrollment(id) ON DELETE RESTRICT,
    decision_type VARCHAR(40) NOT NULL,
    target_level_id BIGINT REFERENCES level(id) ON DELETE RESTRICT,
    decision_date DATE NOT NULL,
    comment TEXT,
    status VARCHAR(30) NOT NULL,
    validated_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    validated_at TIMESTAMPTZ
);

CREATE TABLE assessment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teaching_assignment_id BIGINT NOT NULL REFERENCES teaching_assignment(id) ON DELETE RESTRICT,
    academic_period_id BIGINT NOT NULL REFERENCES academic_period(id) ON DELETE RESTRICT,
    assessment_type_id BIGINT NOT NULL REFERENCES assessment_type(id) ON DELETE RESTRICT,
    title VARCHAR(200) NOT NULL,
    assessment_date DATE NOT NULL,
    coefficient NUMERIC(6,2) NOT NULL,
    max_score NUMERIC(8,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    visibility_status VARCHAR(30) NOT NULL,
    published_at TIMESTAMPTZ,
    description TEXT,
    created_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    locked_at TIMESTAMPTZ
);

CREATE TABLE enrollment_class_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_enrollment_id BIGINT NOT NULL REFERENCES student_enrollment(id) ON DELETE RESTRICT,
    class_group_id BIGINT NOT NULL REFERENCES class_group(id) ON DELETE RESTRICT,
    start_date DATE NOT NULL,
    end_date DATE,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE expense (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_number VARCHAR(60) NOT NULL,
    expense_date DATE NOT NULL,
    expense_category_id BIGINT NOT NULL REFERENCES expense_category(id) ON DELETE RESTRICT,
    provider_id BIGINT REFERENCES provider(id) ON DELETE RESTRICT,
    campus_id BIGINT REFERENCES campus(id) ON DELETE RESTRICT,
    provider_invoice_id BIGINT REFERENCES provider_invoice(id) ON DELETE RESTRICT,
    internal_request_id BIGINT REFERENCES internal_request(id) ON DELETE RESTRICT,
    description TEXT NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    requested_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    validated_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    validated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE family_credit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guardian_id BIGINT NOT NULL REFERENCES guardian(id) ON DELETE RESTRICT,
    source_payment_id BIGINT NOT NULL REFERENCES payment(id) ON DELETE RESTRICT,
    initial_amount NUMERIC(14,2) NOT NULL,
    remaining_amount NUMERIC(14,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE goods_receipt_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_receipt_id BIGINT NOT NULL REFERENCES goods_receipt(id) ON DELETE RESTRICT,
    purchase_order_item_id BIGINT NOT NULL REFERENCES purchase_order_item(id) ON DELETE RESTRICT,
    quantity_received NUMERIC(12,3) NOT NULL,
    condition VARCHAR(40),
    notes TEXT
);

CREATE TABLE payroll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT,
    payroll_period_id BIGINT NOT NULL REFERENCES payroll_period(id) ON DELETE RESTRICT,
    compensation_plan_id BIGINT NOT NULL REFERENCES compensation_plan(id) ON DELETE RESTRICT,
    version_number INTEGER NOT NULL,
    compensation_type VARCHAR(30) NOT NULL,
    base_salary NUMERIC(14,2) NOT NULL,
    fixed_part NUMERIC(14,2) NOT NULL,
    hourly_rate NUMERIC(14,2),
    theoretical_days NUMERIC(6,2),
    worked_days NUMERIC(6,2),
    absent_days NUMERIC(6,2),
    regular_hours NUMERIC(8,2) NOT NULL,
    replacement_hours NUMERIC(8,2) NOT NULL,
    extra_hours NUMERIC(8,2) NOT NULL,
    hourly_amount NUMERIC(14,2) NOT NULL,
    absence_deduction NUMERIC(14,2) NOT NULL,
    bonus_total NUMERIC(14,2) NOT NULL,
    deduction_total NUMERIC(14,2) NOT NULL,
    reimbursement_total NUMERIC(14,2) NOT NULL,
    gross_salary NUMERIC(14,2) NOT NULL,
    contributable_salary NUMERIC(14,2) NOT NULL,
    employee_social_contribution NUMERIC(14,2) NOT NULL,
    employer_social_contribution NUMERIC(14,2) NOT NULL,
    other_contributions NUMERIC(14,2) NOT NULL,
    taxable_amount NUMERIC(14,2) NOT NULL,
    tax_amount NUMERIC(14,2) NOT NULL,
    net_salary NUMERIC(14,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    calculated_at TIMESTAMPTZ,
    calculated_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    validated_at TIMESTAMPTZ,
    validated_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE provider_payment_allocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_payment_id BIGINT NOT NULL REFERENCES provider_payment(id) ON DELETE RESTRICT,
    provider_invoice_id BIGINT NOT NULL REFERENCES provider_invoice(id) ON DELETE RESTRICT,
    amount NUMERIC(14,2) NOT NULL
);

CREATE TABLE refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES payment(id) ON DELETE RESTRICT,
    refund_date TIMESTAMPTZ NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    payment_method_id BIGINT NOT NULL REFERENCES payment_method(id) ON DELETE RESTRICT,
    reason TEXT NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    validated_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    validated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE registration_consent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_case_id BIGINT NOT NULL REFERENCES registration_case(id) ON DELETE RESTRICT,
    consent_type VARCHAR(50) NOT NULL,
    accepted BOOLEAN NOT NULL,
    accepted_at TIMESTAMPTZ,
    accepted_by_guardian_id BIGINT REFERENCES guardian(id) ON DELETE RESTRICT,
    notes TEXT
);

CREATE TABLE registration_document_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_case_id BIGINT NOT NULL REFERENCES registration_case(id) ON DELETE RESTRICT,
    requirement_id BIGINT NOT NULL REFERENCES registration_document_requirement(id) ON DELETE RESTRICT,
    provided BOOLEAN NOT NULL,
    provided_at TIMESTAMPTZ,
    verified BOOLEAN NOT NULL,
    verified_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    verified_at TIMESTAMPTZ,
    notes TEXT
);

CREATE TABLE report_card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
    student_enrollment_id BIGINT NOT NULL REFERENCES student_enrollment(id) ON DELETE RESTRICT,
    academic_period_id BIGINT NOT NULL REFERENCES academic_period(id) ON DELETE RESTRICT,
    version_number INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,
    general_average NUMERIC(8,4),
    class_rank INTEGER,
    class_size INTEGER,
    absence_count INTEGER NOT NULL,
    justified_absence_count INTEGER NOT NULL,
    late_count INTEGER NOT NULL,
    general_observation TEXT,
    generated_at TIMESTAMPTZ NOT NULL,
    generated_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    validated_at TIMESTAMPTZ,
    validated_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    published_at TIMESTAMPTZ,
    replaced_by_report_card_id BIGINT
);

CREATE TABLE schedule_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teaching_assignment_id BIGINT NOT NULL REFERENCES teaching_assignment(id) ON DELETE RESTRICT,
    day_of_week VARCHAR(15) NOT NULL,
    time_slot_id BIGINT NOT NULL REFERENCES time_slot(id) ON DELETE RESTRICT,
    room_id BIGINT REFERENCES room(id) ON DELETE RESTRICT,
    valid_from DATE NOT NULL,
    valid_until DATE,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE student_boarding_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES transport_trip(id) ON DELETE RESTRICT,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
    stop_id BIGINT REFERENCES transport_stop(id) ON DELETE RESTRICT,
    event_type VARCHAR(30) NOT NULL,
    event_time TIMESTAMPTZ NOT NULL,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    recorded_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    notes TEXT
);

CREATE TABLE student_charge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_enrollment_id BIGINT REFERENCES student_enrollment(id) ON DELETE RESTRICT,
    registration_case_id BIGINT REFERENCES registration_case(id) ON DELETE RESTRICT,
    fee_type_id BIGINT NOT NULL REFERENCES fee_type(id) ON DELETE RESTRICT,
    tariff_id BIGINT REFERENCES tariff(id) ON DELETE RESTRICT,
    label VARCHAR(200) NOT NULL,
    original_amount NUMERIC(14,2) NOT NULL,
    discount_amount NUMERIC(14,2) NOT NULL,
    final_amount NUMERIC(14,2) NOT NULL,
    due_date DATE,
    billing_period_start DATE,
    billing_period_end DATE,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    cancelled_at TIMESTAMPTZ,
    cancellation_reason TEXT
);

CREATE TABLE student_discount (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_enrollment_id BIGINT NOT NULL REFERENCES student_enrollment(id) ON DELETE RESTRICT,
    discount_rule_id BIGINT REFERENCES discount_rule(id) ON DELETE RESTRICT,
    fee_type_id BIGINT REFERENCES fee_type(id) ON DELETE RESTRICT,
    discount_type VARCHAR(30) NOT NULL,
    value NUMERIC(14,2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    reason TEXT,
    status VARCHAR(30) NOT NULL,
    approved_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    approved_at TIMESTAMPTZ,
    created_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE student_period_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
    student_enrollment_id BIGINT NOT NULL REFERENCES student_enrollment(id) ON DELETE RESTRICT,
    academic_period_id BIGINT NOT NULL REFERENCES academic_period(id) ON DELETE RESTRICT,
    general_average NUMERIC(8,4),
    total_weighted_points NUMERIC(14,4),
    total_coefficients NUMERIC(10,2),
    class_rank INTEGER,
    class_size INTEGER,
    absence_count INTEGER NOT NULL,
    justified_absence_count INTEGER NOT NULL,
    late_count INTEGER NOT NULL,
    late_minutes INTEGER NOT NULL,
    general_observation TEXT,
    decision VARCHAR(50),
    status VARCHAR(30) NOT NULL,
    calculated_at TIMESTAMPTZ,
    validated_at TIMESTAMPTZ
);

CREATE TABLE student_registration_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_case_id BIGINT NOT NULL REFERENCES registration_case(id) ON DELETE RESTRICT,
    previous_school VARCHAR(200),
    previous_class VARCHAR(100),
    notes TEXT
);

CREATE TABLE student_subject_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
    academic_period_id BIGINT NOT NULL REFERENCES academic_period(id) ON DELETE RESTRICT,
    teaching_assignment_id BIGINT NOT NULL REFERENCES teaching_assignment(id) ON DELETE RESTRICT,
    subject_id BIGINT NOT NULL REFERENCES subject(id) ON DELETE RESTRICT,
    average_score NUMERIC(8,4),
    subject_coefficient NUMERIC(6,2) NOT NULL,
    weighted_points NUMERIC(12,4),
    teacher_observation TEXT,
    status VARCHAR(30) NOT NULL,
    calculated_at TIMESTAMPTZ,
    validated_at TIMESTAMPTZ
);

CREATE TABLE student_transport_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_enrollment_id BIGINT NOT NULL REFERENCES student_enrollment(id) ON DELETE RESTRICT,
    route_id BIGINT NOT NULL REFERENCES transport_route(id) ON DELETE RESTRICT,
    boarding_stop_id BIGINT REFERENCES transport_stop(id) ON DELETE RESTRICT,
    dropoff_stop_id BIGINT REFERENCES transport_stop(id) ON DELETE RESTRICT,
    direction VARCHAR(30) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE transport_incident (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES transport_trip(id) ON DELETE RESTRICT,
    vehicle_id BIGINT REFERENCES vehicle(id) ON DELETE RESTRICT,
    driver_profile_id BIGINT REFERENCES driver_profile(id) ON DELETE RESTRICT,
    incident_type VARCHAR(40) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    description TEXT NOT NULL,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    reported_at TIMESTAMPTZ NOT NULL,
    reported_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL
);

CREATE TABLE trip_current_location (
    trip_id BIGINT NOT NULL REFERENCES transport_trip(id) ON DELETE RESTRICT,
    latitude NUMERIC(10,7) NOT NULL,
    longitude NUMERIC(10,7) NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL,
    accuracy_meters NUMERIC(8,2),
    speed NUMERIC(8,2),
    heading NUMERIC(8,2),
    PRIMARY KEY (trip_id)
);

CREATE TABLE trip_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES transport_trip(id) ON DELETE RESTRICT,
    latitude NUMERIC(10,7) NOT NULL,
    longitude NUMERIC(10,7) NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL,
    accuracy_meters NUMERIC(8,2),
    speed NUMERIC(8,2),
    heading NUMERIC(8,2),
    source VARCHAR(30) NOT NULL
);

CREATE TABLE cash_movement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_register_session_id BIGINT NOT NULL REFERENCES cash_register_session(id) ON DELETE RESTRICT,
    movement_type VARCHAR(40) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    payment_id BIGINT REFERENCES payment(id) ON DELETE RESTRICT,
    refund_id BIGINT REFERENCES refund(id) ON DELETE RESTRICT,
    salary_payment_id BIGINT,
    provider_payment_id BIGINT,
    reference VARCHAR(150),
    description TEXT,
    created_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE class_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_entry_id BIGINT REFERENCES schedule_entry(id) ON DELETE RESTRICT,
    session_date DATE NOT NULL,
    teacher_id BIGINT NOT NULL REFERENCES teacher(id) ON DELETE RESTRICT,
    class_group_id BIGINT NOT NULL REFERENCES class_group(id) ON DELETE RESTRICT,
    subject_id BIGINT NOT NULL REFERENCES subject(id) ON DELETE RESTRICT,
    time_slot_id BIGINT NOT NULL REFERENCES time_slot(id) ON DELETE RESTRICT,
    room_id BIGINT REFERENCES room(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL,
    generated_from_schedule BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE grade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE RESTRICT,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
    score NUMERIC(8,2),
    grade_status VARCHAR(30) NOT NULL,
    observation TEXT,
    entered_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    entered_at TIMESTAMPTZ NOT NULL,
    updated_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE grade_unlock_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_period_id BIGINT NOT NULL REFERENCES academic_period(id) ON DELETE RESTRICT,
    assessment_id BIGINT REFERENCES assessment(id) ON DELETE RESTRICT,
    teacher_id BIGINT NOT NULL REFERENCES teacher(id) ON DELETE RESTRICT,
    reason TEXT NOT NULL,
    requested_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    requested_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(30) NOT NULL,
    approved_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    approved_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ
);

CREATE TABLE payment_allocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES payment(id) ON DELETE RESTRICT,
    student_charge_id BIGINT NOT NULL REFERENCES student_charge(id) ON DELETE RESTRICT,
    amount NUMERIC(14,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE payroll_contribution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id BIGINT NOT NULL REFERENCES payroll(id) ON DELETE RESTRICT,
    contribution_type_id BIGINT NOT NULL REFERENCES contribution_type(id) ON DELETE RESTRICT,
    base_amount NUMERIC(14,2) NOT NULL,
    rate NUMERIC(10,6) NOT NULL,
    employee_amount NUMERIC(14,2) NOT NULL,
    employer_amount NUMERIC(14,2) NOT NULL
);

CREATE TABLE payroll_tax (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id BIGINT NOT NULL REFERENCES payroll(id) ON DELETE RESTRICT,
    tax_type VARCHAR(60) NOT NULL,
    taxable_base NUMERIC(14,2) NOT NULL,
    rate NUMERIC(10,6),
    amount NUMERIC(14,2) NOT NULL
);

CREATE TABLE payroll_validation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id BIGINT NOT NULL REFERENCES payroll(id) ON DELETE RESTRICT,
    validation_step VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL,
    validated_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    validated_at TIMESTAMPTZ,
    comment TEXT
);

CREATE TABLE payslip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id BIGINT NOT NULL REFERENCES payroll(id) ON DELETE RESTRICT,
    payslip_number VARCHAR(60) NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL,
    generated_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL
);

CREATE TABLE report_card_subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_card_id BIGINT NOT NULL REFERENCES report_card(id) ON DELETE RESTRICT,
    subject_id BIGINT NOT NULL REFERENCES subject(id) ON DELETE RESTRICT,
    subject_name_snapshot VARCHAR(150) NOT NULL,
    teacher_name_snapshot VARCHAR(220),
    average_score NUMERIC(8,4),
    coefficient NUMERIC(6,2) NOT NULL,
    weighted_points NUMERIC(12,4),
    observation TEXT,
    display_order INTEGER NOT NULL
);

CREATE TABLE salary_payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id BIGINT NOT NULL REFERENCES payroll(id) ON DELETE RESTRICT,
    payment_date TIMESTAMPTZ NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    payment_method_id BIGINT NOT NULL REFERENCES payment_method(id) ON DELETE RESTRICT,
    cash_register_session_id BIGINT REFERENCES cash_register_session(id) ON DELETE RESTRICT,
    reference VARCHAR(150),
    status VARCHAR(30) NOT NULL,
    paid_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL,
    cancelled_at TIMESTAMPTZ,
    cancellation_reason TEXT
);

CREATE TABLE schedule_exception (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_entry_id BIGINT NOT NULL REFERENCES schedule_entry(id) ON DELETE RESTRICT,
    exception_date DATE NOT NULL,
    exception_type VARCHAR(40) NOT NULL,
    replacement_teacher_id BIGINT REFERENCES teacher(id) ON DELETE RESTRICT,
    replacement_subject_id BIGINT REFERENCES subject(id) ON DELETE RESTRICT,
    replacement_room_id BIGINT REFERENCES room(id) ON DELETE RESTRICT,
    replacement_time_slot_id BIGINT REFERENCES time_slot(id) ON DELETE RESTRICT,
    reason TEXT,
    created_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE trip_student (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES transport_trip(id) ON DELETE RESTRICT,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
    subscription_id BIGINT NOT NULL REFERENCES student_transport_subscription(id) ON DELETE RESTRICT,
    boarding_stop_id BIGINT REFERENCES transport_stop(id) ON DELETE RESTRICT,
    dropoff_stop_id BIGINT REFERENCES transport_stop(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL
);

CREATE TABLE employee_work_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE RESTRICT,
    class_session_id BIGINT REFERENCES class_session(id) ON DELETE RESTRICT,
    work_date DATE NOT NULL,
    work_type VARCHAR(40) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_reference_id BIGINT,
    status VARCHAR(30) NOT NULL,
    validated_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    validated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE grade_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_id BIGINT NOT NULL REFERENCES grade(id) ON DELETE RESTRICT,
    old_score NUMERIC(8,2),
    new_score NUMERIC(8,2),
    old_status VARCHAR(30),
    new_status VARCHAR(30),
    old_observation TEXT,
    new_observation TEXT,
    reason TEXT NOT NULL,
    changed_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    changed_at TIMESTAMPTZ NOT NULL,
    unlock_request_id BIGINT REFERENCES grade_unlock_request(id) ON DELETE RESTRICT
);

CREATE TABLE student_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_session_id BIGINT NOT NULL REFERENCES class_session(id) ON DELETE RESTRICT,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
    attendance_status VARCHAR(30) NOT NULL,
    late_minutes INTEGER,
    reason TEXT,
    justified BOOLEAN NOT NULL,
    recorded_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    recorded_at TIMESTAMPTZ NOT NULL,
    validated_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    validated_at TIMESTAMPTZ,
    notes TEXT
);

CREATE TABLE teacher_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_session_id BIGINT NOT NULL REFERENCES class_session(id) ON DELETE RESTRICT,
    teacher_id BIGINT NOT NULL REFERENCES teacher(id) ON DELETE RESTRICT,
    attendance_status VARCHAR(30) NOT NULL,
    late_minutes INTEGER,
    reason TEXT,
    validation_status VARCHAR(30) NOT NULL,
    recorded_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    recorded_at TIMESTAMPTZ NOT NULL,
    validated_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    validated_at TIMESTAMPTZ,
    notes TEXT
);

CREATE TABLE teacher_replacement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_session_id BIGINT NOT NULL REFERENCES class_session(id) ON DELETE RESTRICT,
    absent_teacher_id BIGINT NOT NULL REFERENCES teacher(id) ON DELETE RESTRICT,
    replacement_teacher_id BIGINT NOT NULL REFERENCES teacher(id) ON DELETE RESTRICT,
    reason TEXT,
    status VARCHAR(30) NOT NULL,
    assigned_by BIGINT NOT NULL REFERENCES user_account(id) ON DELETE RESTRICT,
    assigned_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE attendance_justification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_attendance_id BIGINT NOT NULL REFERENCES student_attendance(id) ON DELETE RESTRICT,
    submitted_by_guardian_id BIGINT REFERENCES guardian(id) ON DELETE RESTRICT,
    reason TEXT NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(30) NOT NULL,
    reviewed_by BIGINT REFERENCES user_account(id) ON DELETE RESTRICT,
    reviewed_at TIMESTAMPTZ,
    review_note TEXT
);

ALTER TABLE cash_movement ADD CONSTRAINT fk_cash_movement_salary_payment_id FOREIGN KEY (salary_payment_id) REFERENCES salary_payment(id) ON DELETE RESTRICT;
ALTER TABLE cash_movement ADD CONSTRAINT fk_cash_movement_provider_payment_id FOREIGN KEY (provider_payment_id) REFERENCES provider_payment(id) ON DELETE RESTRICT;

ALTER TABLE user_account ADD CONSTRAINT uq_user_account_person_id UNIQUE (person_id);
ALTER TABLE user_account ADD CONSTRAINT uq_user_account_username UNIQUE (username);
ALTER TABLE role ADD CONSTRAINT uq_role_code UNIQUE (code);
ALTER TABLE permission ADD CONSTRAINT uq_permission_code UNIQUE (code);
ALTER TABLE school_year ADD CONSTRAINT uq_school_year_code UNIQUE (code);
ALTER TABLE cycle ADD CONSTRAINT uq_cycle_code UNIQUE (code);
ALTER TABLE level ADD CONSTRAINT uq_level_code UNIQUE (code);
ALTER TABLE campus ADD CONSTRAINT uq_campus_code UNIQUE (code);
ALTER TABLE room ADD CONSTRAINT uq_room_campus_id_code UNIQUE (campus_id, code);
ALTER TABLE class_group ADD CONSTRAINT uq_class_group_school_year_id_code UNIQUE (school_year_id, code);
ALTER TABLE time_slot ADD CONSTRAINT uq_time_slot_code UNIQUE (code);
ALTER TABLE student ADD CONSTRAINT uq_student_person_id UNIQUE (person_id);
ALTER TABLE student ADD CONSTRAINT uq_student_student_number UNIQUE (student_number);
ALTER TABLE guardian ADD CONSTRAINT uq_guardian_person_id UNIQUE (person_id);
ALTER TABLE student_guardian ADD CONSTRAINT uq_student_guardian_student_id_guardian_id UNIQUE (student_id, guardian_id);
ALTER TABLE student_family_info ADD CONSTRAINT uq_student_family_info_student_id UNIQUE (student_id);
ALTER TABLE student_medical_info ADD CONSTRAINT uq_student_medical_info_student_id UNIQUE (student_id);
ALTER TABLE registration_case ADD CONSTRAINT uq_registration_case_student_id_school_year_id UNIQUE (student_id, school_year_id);
ALTER TABLE student_registration_info ADD CONSTRAINT uq_student_registration_info_registration_case_id UNIQUE (registration_case_id);
ALTER TABLE registration_consent ADD CONSTRAINT uq_registration_consent_registration_case_id_consent_type UNIQUE (registration_case_id, consent_type);
ALTER TABLE registration_document_requirement ADD CONSTRAINT uq_registration_document_requirement_code UNIQUE (code);
ALTER TABLE registration_document_status ADD CONSTRAINT uq_registration_document_status_registration_case_id_requirement_id UNIQUE (registration_case_id, requirement_id);
ALTER TABLE student_enrollment ADD CONSTRAINT uq_student_enrollment_student_id_school_year_id UNIQUE (student_id, school_year_id);
ALTER TABLE employee ADD CONSTRAINT uq_employee_person_id UNIQUE (person_id);
ALTER TABLE employee ADD CONSTRAINT uq_employee_employee_number UNIQUE (employee_number);
ALTER TABLE employee_medical_info ADD CONSTRAINT uq_employee_medical_info_employee_id UNIQUE (employee_id);
ALTER TABLE teacher ADD CONSTRAINT uq_teacher_employee_id UNIQUE (employee_id);
ALTER TABLE subject ADD CONSTRAINT uq_subject_code UNIQUE (code);
ALTER TABLE level_subject ADD CONSTRAINT uq_level_subject_school_year_id_level_id_subject_id UNIQUE (school_year_id, level_id, subject_id);
ALTER TABLE fee_type ADD CONSTRAINT uq_fee_type_code UNIQUE (code);
ALTER TABLE payment_method ADD CONSTRAINT uq_payment_method_code UNIQUE (code);
ALTER TABLE cash_register ADD CONSTRAINT uq_cash_register_code UNIQUE (code);
ALTER TABLE payment ADD CONSTRAINT uq_payment_payment_number UNIQUE (payment_number);
ALTER TABLE payment_allocation ADD CONSTRAINT uq_payment_allocation_payment_id_student_charge_id UNIQUE (payment_id, student_charge_id);
ALTER TABLE payroll_period ADD CONSTRAINT uq_payroll_period_year_month UNIQUE (year, month);
ALTER TABLE payroll ADD CONSTRAINT uq_payroll_employee_id_payroll_period_id_version_number UNIQUE (employee_id, payroll_period_id, version_number);
ALTER TABLE payslip ADD CONSTRAINT uq_payslip_payslip_number UNIQUE (payslip_number);
ALTER TABLE academic_period ADD CONSTRAINT uq_academic_period_school_year_id_code UNIQUE (school_year_id, code);
ALTER TABLE assessment_type ADD CONSTRAINT uq_assessment_type_code UNIQUE (code);
ALTER TABLE grade ADD CONSTRAINT uq_grade_assessment_id_student_id UNIQUE (assessment_id, student_id);
ALTER TABLE student_subject_result ADD CONSTRAINT uq_student_subject_result_student_id_academic_period_id_teaching_assignment_id UNIQUE (student_id, academic_period_id, teaching_assignment_id);
ALTER TABLE student_period_result ADD CONSTRAINT uq_student_period_result_student_id_academic_period_id UNIQUE (student_id, academic_period_id);
ALTER TABLE report_card ADD CONSTRAINT uq_report_card_student_id_academic_period_id_version_number UNIQUE (student_id, academic_period_id, version_number);
ALTER TABLE transport_route ADD CONSTRAINT uq_transport_route_school_year_id_code UNIQUE (school_year_id, code);
ALTER TABLE transport_stop ADD CONSTRAINT uq_transport_stop_code UNIQUE (code);
ALTER TABLE route_stop ADD CONSTRAINT uq_route_stop_route_id_sequence_number UNIQUE (route_id, sequence_number);
ALTER TABLE route_stop ADD CONSTRAINT uq_route_stop_route_id_stop_id UNIQUE (route_id, stop_id);
ALTER TABLE vehicle ADD CONSTRAINT uq_vehicle_registration_number UNIQUE (registration_number);
ALTER TABLE driver_profile ADD CONSTRAINT uq_driver_profile_employee_id UNIQUE (employee_id);
ALTER TABLE driver_profile ADD CONSTRAINT uq_driver_profile_license_number UNIQUE (license_number);
ALTER TABLE trip_student ADD CONSTRAINT uq_trip_student_trip_id_student_id UNIQUE (trip_id, student_id);
ALTER TABLE provider_category ADD CONSTRAINT uq_provider_category_code UNIQUE (code);
ALTER TABLE provider ADD CONSTRAINT uq_provider_code UNIQUE (code);
ALTER TABLE expense_category ADD CONSTRAINT uq_expense_category_code UNIQUE (code);
ALTER TABLE internal_request ADD CONSTRAINT uq_internal_request_request_number UNIQUE (request_number);
ALTER TABLE purchase_order ADD CONSTRAINT uq_purchase_order_order_number UNIQUE (order_number);
ALTER TABLE provider_invoice ADD CONSTRAINT uq_provider_invoice_provider_id_invoice_number UNIQUE (provider_id, invoice_number);
ALTER TABLE expense ADD CONSTRAINT uq_expense_expense_number UNIQUE (expense_number);
ALTER TABLE asset ADD CONSTRAINT uq_asset_asset_code UNIQUE (asset_code);
ALTER TABLE push_device ADD CONSTRAINT uq_push_device_device_token UNIQUE (device_token);

ALTER TABLE school_year ADD CONSTRAINT ck_school_year_dates CHECK (end_date > start_date);
ALTER TABLE time_slot ADD CONSTRAINT ck_time_slot_times CHECK (end_time > start_time);
ALTER TABLE student_family_info ADD CONSTRAINT ck_student_family_counts CHECK (COALESCE(number_of_brothers,0) >= 0 AND COALESCE(number_of_sisters,0) >= 0);
ALTER TABLE employment_contract ADD CONSTRAINT ck_employment_contract_dates CHECK (end_date IS NULL OR end_date >= start_date);
ALTER TABLE student_charge ADD CONSTRAINT ck_student_charge_owner CHECK ((student_enrollment_id IS NOT NULL) <> (registration_case_id IS NOT NULL));
ALTER TABLE student_charge ADD CONSTRAINT ck_student_charge_amounts CHECK (original_amount >= 0 AND discount_amount >= 0 AND final_amount >= 0);
ALTER TABLE student_charge ADD CONSTRAINT ck_student_charge_period CHECK (billing_period_end IS NULL OR billing_period_start IS NULL OR billing_period_end >= billing_period_start);
ALTER TABLE payment ADD CONSTRAINT ck_payment_amount CHECK (total_amount > 0);
ALTER TABLE payment_allocation ADD CONSTRAINT ck_payment_allocation_amount CHECK (amount > 0);
ALTER TABLE family_credit ADD CONSTRAINT ck_family_credit_amounts CHECK (initial_amount >= 0 AND remaining_amount >= 0 AND remaining_amount <= initial_amount);
ALTER TABLE refund ADD CONSTRAINT ck_refund_amount CHECK (amount > 0);
ALTER TABLE cash_register_session ADD CONSTRAINT ck_cash_balances CHECK (opening_balance >= 0);
ALTER TABLE cash_movement ADD CONSTRAINT ck_cash_movement_amount CHECK (amount > 0);
ALTER TABLE teacher_attendance ADD CONSTRAINT ck_teacher_late CHECK (late_minutes IS NULL OR late_minutes >= 0);
ALTER TABLE employee_work_unit ADD CONSTRAINT ck_work_unit_duration CHECK (duration_minutes > 0);
ALTER TABLE student_attendance ADD CONSTRAINT ck_student_late CHECK (late_minutes IS NULL OR late_minutes >= 0);
ALTER TABLE compensation_plan ADD CONSTRAINT ck_compensation_dates CHECK (effective_until IS NULL OR effective_until >= effective_from);
ALTER TABLE teacher_rate ADD CONSTRAINT ck_teacher_rate CHECK (hourly_rate >= 0 AND (effective_until IS NULL OR effective_until >= effective_from));
ALTER TABLE employee_leave ADD CONSTRAINT ck_employee_leave_dates CHECK (end_date >= start_date);
ALTER TABLE payroll_period ADD CONSTRAINT ck_payroll_period CHECK (month BETWEEN 1 AND 12 AND end_date >= start_date);
ALTER TABLE payroll ADD CONSTRAINT ck_payroll_version CHECK (version_number >= 1);
ALTER TABLE salary_payment ADD CONSTRAINT ck_salary_payment_amount CHECK (amount > 0);
ALTER TABLE academic_period ADD CONSTRAINT ck_academic_period_dates CHECK (end_date >= start_date);
ALTER TABLE assessment ADD CONSTRAINT ck_assessment_values CHECK (coefficient > 0 AND max_score > 0);
ALTER TABLE grade ADD CONSTRAINT ck_grade_score_nonnegative CHECK (score IS NULL OR score >= 0);
ALTER TABLE subject_coefficient ADD CONSTRAINT ck_subject_coefficient CHECK (coefficient > 0);
ALTER TABLE route_stop ADD CONSTRAINT ck_route_stop_sequence CHECK (sequence_number > 0);
ALTER TABLE vehicle ADD CONSTRAINT ck_vehicle_capacity CHECK (capacity > 0);
ALTER TABLE transport_stop ADD CONSTRAINT ck_transport_stop_coords CHECK ((latitude IS NULL OR latitude BETWEEN -90 AND 90) AND (longitude IS NULL OR longitude BETWEEN -180 AND 180));
ALTER TABLE trip_location ADD CONSTRAINT ck_trip_location_coords CHECK (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180);
ALTER TABLE trip_current_location ADD CONSTRAINT ck_trip_current_coords CHECK (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180);
ALTER TABLE internal_request_item ADD CONSTRAINT ck_request_item_quantity CHECK (quantity > 0);
ALTER TABLE purchase_order_item ADD CONSTRAINT ck_po_item_quantity CHECK (quantity > 0 AND unit_price >= 0);
ALTER TABLE goods_receipt_item ADD CONSTRAINT ck_receipt_item_quantity CHECK (quantity_received > 0);
ALTER TABLE provider_invoice ADD CONSTRAINT ck_provider_invoice_amounts CHECK (subtotal >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0);
ALTER TABLE expense ADD CONSTRAINT ck_expense_amount CHECK (amount > 0);
ALTER TABLE provider_payment ADD CONSTRAINT ck_provider_payment_amount CHECK (amount > 0);
ALTER TABLE provider_payment_allocation ADD CONSTRAINT ck_provider_payment_allocation CHECK (amount > 0);
ALTER TABLE maintenance_request ADD CONSTRAINT ck_maintenance_target CHECK (NOT (asset_id IS NOT NULL AND vehicle_id IS NOT NULL));

CREATE INDEX idx_expense_category_parent_category_id ON expense_category (parent_category_id);
CREATE INDEX idx_asset_campus_id ON asset (campus_id);
CREATE INDEX idx_asset_provider_id ON asset (provider_id);
CREATE INDEX idx_cash_register_campus_id ON cash_register (campus_id);
CREATE INDEX idx_discount_rule_school_year_id ON discount_rule (school_year_id);
CREATE INDEX idx_discount_rule_fee_type_id ON discount_rule (fee_type_id);
CREATE INDEX idx_employee_person_id ON employee (person_id);
CREATE INDEX idx_employee_campus_id ON employee (campus_id);
CREATE INDEX idx_guardian_person_id ON guardian (person_id);
CREATE INDEX idx_level_cycle_id ON level (cycle_id);
CREATE INDEX idx_payroll_parameter_school_year_id ON payroll_parameter (school_year_id);
CREATE INDEX idx_provider_category_assignment_provider_id ON provider_category_assignment (provider_id);
CREATE INDEX idx_provider_category_assignment_category_id ON provider_category_assignment (category_id);
CREATE INDEX idx_provider_contract_provider_id ON provider_contract (provider_id);
CREATE INDEX idx_provider_contract_campus_id ON provider_contract (campus_id);
CREATE INDEX idx_recurring_expense_provider_id ON recurring_expense (provider_id);
CREATE INDEX idx_recurring_expense_expense_category_id ON recurring_expense (expense_category_id);
CREATE INDEX idx_recurring_expense_campus_id ON recurring_expense (campus_id);
CREATE INDEX idx_role_permission_role_id ON role_permission (role_id);
CREATE INDEX idx_role_permission_permission_id ON role_permission (permission_id);
CREATE INDEX idx_room_campus_id ON room (campus_id);
CREATE INDEX idx_school_calendar_exception_school_year_id ON school_calendar_exception (school_year_id);
CREATE INDEX idx_school_calendar_exception_campus_id ON school_calendar_exception (campus_id);
CREATE INDEX idx_school_calendar_exception_cycle_id ON school_calendar_exception (cycle_id);
CREATE INDEX idx_student_person_id ON student (person_id);
CREATE INDEX idx_transport_route_school_year_id ON transport_route (school_year_id);
CREATE INDEX idx_transport_route_campus_id ON transport_route (campus_id);
CREATE INDEX idx_user_account_person_id ON user_account (person_id);
CREATE INDEX idx_vehicle_provider_id ON vehicle (provider_id);
CREATE INDEX idx_academic_period_school_year_id ON academic_period (school_year_id);
CREATE INDEX idx_academic_period_locked_by ON academic_period (locked_by);
CREATE INDEX idx_audit_log_user_account_id ON audit_log (user_account_id);
CREATE INDEX idx_authorized_pickup_person_student_id ON authorized_pickup_person (student_id);
CREATE INDEX idx_cash_register_session_cash_register_id ON cash_register_session (cash_register_id);
CREATE INDEX idx_cash_register_session_cashier_id ON cash_register_session (cashier_id);
CREATE INDEX idx_cash_register_session_closed_by ON cash_register_session (closed_by);
CREATE INDEX idx_class_group_school_year_id ON class_group (school_year_id);
CREATE INDEX idx_class_group_level_id ON class_group (level_id);
CREATE INDEX idx_class_group_campus_id ON class_group (campus_id);
CREATE INDEX idx_driver_profile_employee_id ON driver_profile (employee_id);
CREATE INDEX idx_employee_leave_employee_id ON employee_leave (employee_id);
CREATE INDEX idx_employee_leave_leave_type_id ON employee_leave (leave_type_id);
CREATE INDEX idx_employee_leave_approved_by ON employee_leave (approved_by);
CREATE INDEX idx_employee_medical_info_employee_id ON employee_medical_info (employee_id);
CREATE INDEX idx_employee_qualification_employee_id ON employee_qualification (employee_id);
CREATE INDEX idx_employment_contract_employee_id ON employment_contract (employee_id);
CREATE INDEX idx_employment_history_employee_id ON employment_history (employee_id);
CREATE INDEX idx_internal_request_requester_employee_id ON internal_request (requester_employee_id);
CREATE INDEX idx_internal_request_campus_id ON internal_request (campus_id);
CREATE INDEX idx_level_subject_school_year_id ON level_subject (school_year_id);
CREATE INDEX idx_level_subject_level_id ON level_subject (level_id);
CREATE INDEX idx_level_subject_subject_id ON level_subject (subject_id);
CREATE INDEX idx_maintenance_request_asset_id ON maintenance_request (asset_id);
CREATE INDEX idx_maintenance_request_vehicle_id ON maintenance_request (vehicle_id);
CREATE INDEX idx_maintenance_request_campus_id ON maintenance_request (campus_id);
CREATE INDEX idx_maintenance_request_reported_by ON maintenance_request (reported_by);
CREATE INDEX idx_maintenance_request_assigned_provider_id ON maintenance_request (assigned_provider_id);
CREATE INDEX idx_notification_recipient_user_id ON notification (recipient_user_id);
CREATE INDEX idx_payroll_period_school_year_id ON payroll_period (school_year_id);
CREATE INDEX idx_payroll_period_closed_by ON payroll_period (closed_by);
CREATE INDEX idx_purchase_order_provider_id ON purchase_order (provider_id);
CREATE INDEX idx_purchase_order_campus_id ON purchase_order (campus_id);
CREATE INDEX idx_purchase_order_created_by ON purchase_order (created_by);
CREATE INDEX idx_purchase_order_approved_by ON purchase_order (approved_by);
CREATE INDEX idx_push_device_user_account_id ON push_device (user_account_id);
CREATE INDEX idx_recurring_payroll_item_employee_id ON recurring_payroll_item (employee_id);
CREATE INDEX idx_route_stop_route_id ON route_stop (route_id);
CREATE INDEX idx_route_stop_stop_id ON route_stop (stop_id);
CREATE INDEX idx_student_family_info_student_id ON student_family_info (student_id);
CREATE INDEX idx_student_guardian_student_id ON student_guardian (student_id);
CREATE INDEX idx_student_guardian_guardian_id ON student_guardian (guardian_id);
CREATE INDEX idx_student_medical_info_student_id ON student_medical_info (student_id);
CREATE INDEX idx_subject_coefficient_school_year_id ON subject_coefficient (school_year_id);
CREATE INDEX idx_subject_coefficient_level_id ON subject_coefficient (level_id);
CREATE INDEX idx_subject_coefficient_subject_id ON subject_coefficient (subject_id);
CREATE INDEX idx_teacher_employee_id ON teacher (employee_id);
CREATE INDEX idx_transport_staff_assignment_employee_id ON transport_staff_assignment (employee_id);
CREATE INDEX idx_transport_staff_assignment_route_id ON transport_staff_assignment (route_id);
CREATE INDEX idx_user_role_user_account_id ON user_role (user_account_id);
CREATE INDEX idx_user_role_role_id ON user_role (role_id);
CREATE INDEX idx_user_role_assigned_by ON user_role (assigned_by);
CREATE INDEX idx_user_scope_user_account_id ON user_scope (user_account_id);
CREATE INDEX idx_class_teacher_assignment_school_year_id ON class_teacher_assignment (school_year_id);
CREATE INDEX idx_class_teacher_assignment_class_group_id ON class_teacher_assignment (class_group_id);
CREATE INDEX idx_class_teacher_assignment_teacher_id ON class_teacher_assignment (teacher_id);
CREATE INDEX idx_compensation_plan_employee_id ON compensation_plan (employee_id);
CREATE INDEX idx_compensation_plan_school_year_id ON compensation_plan (school_year_id);
CREATE INDEX idx_compensation_plan_employment_contract_id ON compensation_plan (employment_contract_id);
CREATE INDEX idx_compensation_plan_created_by ON compensation_plan (created_by);
CREATE INDEX idx_goods_receipt_purchase_order_id ON goods_receipt (purchase_order_id);
CREATE INDEX idx_goods_receipt_received_by ON goods_receipt (received_by);
CREATE INDEX idx_internal_request_item_internal_request_id ON internal_request_item (internal_request_id);
CREATE INDEX idx_payment_guardian_id ON payment (guardian_id);
CREATE INDEX idx_payment_payment_method_id ON payment (payment_method_id);
CREATE INDEX idx_payment_cashier_id ON payment (cashier_id);
CREATE INDEX idx_payment_cash_register_session_id ON payment (cash_register_session_id);
CREATE INDEX idx_payment_validated_by ON payment (validated_by);
CREATE INDEX idx_payment_cancelled_by ON payment (cancelled_by);
CREATE INDEX idx_payroll_adjustment_employee_id ON payroll_adjustment (employee_id);
CREATE INDEX idx_payroll_adjustment_payroll_period_id ON payroll_adjustment (payroll_period_id);
CREATE INDEX idx_payroll_adjustment_created_by ON payroll_adjustment (created_by);
CREATE INDEX idx_payroll_adjustment_validated_by ON payroll_adjustment (validated_by);
CREATE INDEX idx_provider_invoice_provider_id ON provider_invoice (provider_id);
CREATE INDEX idx_provider_invoice_purchase_order_id ON provider_invoice (purchase_order_id);
CREATE INDEX idx_provider_invoice_campus_id ON provider_invoice (campus_id);
CREATE INDEX idx_provider_payment_provider_id ON provider_payment (provider_id);
CREATE INDEX idx_provider_payment_payment_method_id ON provider_payment (payment_method_id);
CREATE INDEX idx_provider_payment_cash_register_session_id ON provider_payment (cash_register_session_id);
CREATE INDEX idx_provider_payment_paid_by ON provider_payment (paid_by);
CREATE INDEX idx_provider_payment_cancelled_by ON provider_payment (cancelled_by);
CREATE INDEX idx_purchase_order_item_purchase_order_id ON purchase_order_item (purchase_order_id);
CREATE INDEX idx_purchase_order_request_purchase_order_id ON purchase_order_request (purchase_order_id);
CREATE INDEX idx_purchase_order_request_internal_request_id ON purchase_order_request (internal_request_id);
CREATE INDEX idx_registration_case_school_year_id ON registration_case (school_year_id);
CREATE INDEX idx_registration_case_student_id ON registration_case (student_id);
CREATE INDEX idx_registration_case_guardian_id ON registration_case (guardian_id);
CREATE INDEX idx_registration_case_requested_level_id ON registration_case (requested_level_id);
CREATE INDEX idx_registration_case_requested_class_group_id ON registration_case (requested_class_group_id);
CREATE INDEX idx_registration_case_created_by ON registration_case (created_by);
CREATE INDEX idx_request_approval_internal_request_id ON request_approval (internal_request_id);
CREATE INDEX idx_request_approval_approver_id ON request_approval (approver_id);
CREATE INDEX idx_route_vehicle_assignment_route_id ON route_vehicle_assignment (route_id);
CREATE INDEX idx_route_vehicle_assignment_vehicle_id ON route_vehicle_assignment (vehicle_id);
CREATE INDEX idx_route_vehicle_assignment_driver_profile_id ON route_vehicle_assignment (driver_profile_id);
CREATE INDEX idx_student_enrollment_student_id ON student_enrollment (student_id);
CREATE INDEX idx_student_enrollment_school_year_id ON student_enrollment (school_year_id);
CREATE INDEX idx_student_enrollment_current_class_group_id ON student_enrollment (current_class_group_id);
CREATE INDEX idx_student_exit_student_id ON student_exit (student_id);
CREATE INDEX idx_student_exit_school_year_id ON student_exit (school_year_id);
CREATE INDEX idx_student_exit_pickup_person_id ON student_exit (pickup_person_id);
CREATE INDEX idx_student_exit_authorized_by ON student_exit (authorized_by);
CREATE INDEX idx_student_exit_recorded_by ON student_exit (recorded_by);
CREATE INDEX idx_tariff_school_year_id ON tariff (school_year_id);
CREATE INDEX idx_tariff_fee_type_id ON tariff (fee_type_id);
CREATE INDEX idx_tariff_level_id ON tariff (level_id);
CREATE INDEX idx_tariff_class_group_id ON tariff (class_group_id);
CREATE INDEX idx_tariff_campus_id ON tariff (campus_id);
CREATE INDEX idx_teacher_rate_teacher_id ON teacher_rate (teacher_id);
CREATE INDEX idx_teacher_rate_school_year_id ON teacher_rate (school_year_id);
CREATE INDEX idx_teacher_rate_class_group_id ON teacher_rate (class_group_id);
CREATE INDEX idx_teacher_rate_subject_id ON teacher_rate (subject_id);
CREATE INDEX idx_teacher_subject_teacher_id ON teacher_subject (teacher_id);
CREATE INDEX idx_teacher_subject_subject_id ON teacher_subject (subject_id);
CREATE INDEX idx_teaching_assignment_school_year_id ON teaching_assignment (school_year_id);
CREATE INDEX idx_teaching_assignment_teacher_id ON teaching_assignment (teacher_id);
CREATE INDEX idx_teaching_assignment_subject_id ON teaching_assignment (subject_id);
CREATE INDEX idx_teaching_assignment_class_group_id ON teaching_assignment (class_group_id);
CREATE INDEX idx_transport_trip_route_id ON transport_trip (route_id);
CREATE INDEX idx_transport_trip_vehicle_id ON transport_trip (vehicle_id);
CREATE INDEX idx_transport_trip_driver_profile_id ON transport_trip (driver_profile_id);
CREATE INDEX idx_annual_student_decision_student_enrollment_id ON annual_student_decision (student_enrollment_id);
CREATE INDEX idx_annual_student_decision_target_level_id ON annual_student_decision (target_level_id);
CREATE INDEX idx_annual_student_decision_validated_by ON annual_student_decision (validated_by);
CREATE INDEX idx_assessment_teaching_assignment_id ON assessment (teaching_assignment_id);
CREATE INDEX idx_assessment_academic_period_id ON assessment (academic_period_id);
CREATE INDEX idx_assessment_assessment_type_id ON assessment (assessment_type_id);
CREATE INDEX idx_assessment_created_by ON assessment (created_by);
CREATE INDEX idx_enrollment_class_history_student_enrollment_id ON enrollment_class_history (student_enrollment_id);
CREATE INDEX idx_enrollment_class_history_class_group_id ON enrollment_class_history (class_group_id);
CREATE INDEX idx_expense_expense_category_id ON expense (expense_category_id);
CREATE INDEX idx_expense_provider_id ON expense (provider_id);
CREATE INDEX idx_expense_campus_id ON expense (campus_id);
CREATE INDEX idx_expense_provider_invoice_id ON expense (provider_invoice_id);
CREATE INDEX idx_expense_internal_request_id ON expense (internal_request_id);
CREATE INDEX idx_expense_requested_by ON expense (requested_by);
CREATE INDEX idx_expense_validated_by ON expense (validated_by);
CREATE INDEX idx_family_credit_guardian_id ON family_credit (guardian_id);
CREATE INDEX idx_family_credit_source_payment_id ON family_credit (source_payment_id);
CREATE INDEX idx_goods_receipt_item_goods_receipt_id ON goods_receipt_item (goods_receipt_id);
CREATE INDEX idx_goods_receipt_item_purchase_order_item_id ON goods_receipt_item (purchase_order_item_id);
CREATE INDEX idx_payroll_employee_id ON payroll (employee_id);
CREATE INDEX idx_payroll_payroll_period_id ON payroll (payroll_period_id);
CREATE INDEX idx_payroll_compensation_plan_id ON payroll (compensation_plan_id);
CREATE INDEX idx_payroll_calculated_by ON payroll (calculated_by);
CREATE INDEX idx_payroll_validated_by ON payroll (validated_by);
CREATE INDEX idx_provider_payment_allocation_provider_payment_id ON provider_payment_allocation (provider_payment_id);
CREATE INDEX idx_provider_payment_allocation_provider_invoice_id ON provider_payment_allocation (provider_invoice_id);
CREATE INDEX idx_refund_payment_id ON refund (payment_id);
CREATE INDEX idx_refund_payment_method_id ON refund (payment_method_id);
CREATE INDEX idx_refund_created_by ON refund (created_by);
CREATE INDEX idx_refund_validated_by ON refund (validated_by);
CREATE INDEX idx_registration_consent_registration_case_id ON registration_consent (registration_case_id);
CREATE INDEX idx_registration_consent_accepted_by_guardian_id ON registration_consent (accepted_by_guardian_id);
CREATE INDEX idx_registration_document_status_registration_case_id ON registration_document_status (registration_case_id);
CREATE INDEX idx_registration_document_status_requirement_id ON registration_document_status (requirement_id);
CREATE INDEX idx_registration_document_status_verified_by ON registration_document_status (verified_by);
CREATE INDEX idx_report_card_student_id ON report_card (student_id);
CREATE INDEX idx_report_card_student_enrollment_id ON report_card (student_enrollment_id);
CREATE INDEX idx_report_card_academic_period_id ON report_card (academic_period_id);
CREATE INDEX idx_report_card_generated_by ON report_card (generated_by);
CREATE INDEX idx_report_card_validated_by ON report_card (validated_by);
CREATE INDEX idx_report_card_replaced_by_report_card_id ON report_card (replaced_by_report_card_id);
CREATE INDEX idx_schedule_entry_teaching_assignment_id ON schedule_entry (teaching_assignment_id);
CREATE INDEX idx_schedule_entry_time_slot_id ON schedule_entry (time_slot_id);
CREATE INDEX idx_schedule_entry_room_id ON schedule_entry (room_id);
CREATE INDEX idx_student_boarding_event_trip_id ON student_boarding_event (trip_id);
CREATE INDEX idx_student_boarding_event_student_id ON student_boarding_event (student_id);
CREATE INDEX idx_student_boarding_event_stop_id ON student_boarding_event (stop_id);
CREATE INDEX idx_student_boarding_event_recorded_by ON student_boarding_event (recorded_by);
CREATE INDEX idx_student_charge_student_enrollment_id ON student_charge (student_enrollment_id);
CREATE INDEX idx_student_charge_registration_case_id ON student_charge (registration_case_id);
CREATE INDEX idx_student_charge_fee_type_id ON student_charge (fee_type_id);
CREATE INDEX idx_student_charge_tariff_id ON student_charge (tariff_id);
CREATE INDEX idx_student_discount_student_enrollment_id ON student_discount (student_enrollment_id);
CREATE INDEX idx_student_discount_discount_rule_id ON student_discount (discount_rule_id);
CREATE INDEX idx_student_discount_fee_type_id ON student_discount (fee_type_id);
CREATE INDEX idx_student_discount_approved_by ON student_discount (approved_by);
CREATE INDEX idx_student_discount_created_by ON student_discount (created_by);
CREATE INDEX idx_student_period_result_student_id ON student_period_result (student_id);
CREATE INDEX idx_student_period_result_student_enrollment_id ON student_period_result (student_enrollment_id);
CREATE INDEX idx_student_period_result_academic_period_id ON student_period_result (academic_period_id);
CREATE INDEX idx_student_registration_info_registration_case_id ON student_registration_info (registration_case_id);
CREATE INDEX idx_student_subject_result_student_id ON student_subject_result (student_id);
CREATE INDEX idx_student_subject_result_academic_period_id ON student_subject_result (academic_period_id);
CREATE INDEX idx_student_subject_result_teaching_assignment_id ON student_subject_result (teaching_assignment_id);
CREATE INDEX idx_student_subject_result_subject_id ON student_subject_result (subject_id);
CREATE INDEX idx_student_transport_subscription_student_enrollment_id ON student_transport_subscription (student_enrollment_id);
CREATE INDEX idx_student_transport_subscription_route_id ON student_transport_subscription (route_id);
CREATE INDEX idx_student_transport_subscription_boarding_stop_id ON student_transport_subscription (boarding_stop_id);
CREATE INDEX idx_student_transport_subscription_dropoff_stop_id ON student_transport_subscription (dropoff_stop_id);
CREATE INDEX idx_transport_incident_trip_id ON transport_incident (trip_id);
CREATE INDEX idx_transport_incident_vehicle_id ON transport_incident (vehicle_id);
CREATE INDEX idx_transport_incident_driver_profile_id ON transport_incident (driver_profile_id);
CREATE INDEX idx_transport_incident_reported_by ON transport_incident (reported_by);
CREATE INDEX idx_trip_location_trip_id ON trip_location (trip_id);
CREATE INDEX idx_cash_movement_cash_register_session_id ON cash_movement (cash_register_session_id);
CREATE INDEX idx_cash_movement_payment_id ON cash_movement (payment_id);
CREATE INDEX idx_cash_movement_refund_id ON cash_movement (refund_id);
CREATE INDEX idx_cash_movement_salary_payment_id ON cash_movement (salary_payment_id);
CREATE INDEX idx_cash_movement_provider_payment_id ON cash_movement (provider_payment_id);
CREATE INDEX idx_cash_movement_created_by ON cash_movement (created_by);
CREATE INDEX idx_class_session_schedule_entry_id ON class_session (schedule_entry_id);
CREATE INDEX idx_class_session_teacher_id ON class_session (teacher_id);
CREATE INDEX idx_class_session_class_group_id ON class_session (class_group_id);
CREATE INDEX idx_class_session_subject_id ON class_session (subject_id);
CREATE INDEX idx_class_session_time_slot_id ON class_session (time_slot_id);
CREATE INDEX idx_class_session_room_id ON class_session (room_id);
CREATE INDEX idx_grade_assessment_id ON grade (assessment_id);
CREATE INDEX idx_grade_student_id ON grade (student_id);
CREATE INDEX idx_grade_entered_by ON grade (entered_by);
CREATE INDEX idx_grade_updated_by ON grade (updated_by);
CREATE INDEX idx_grade_unlock_request_academic_period_id ON grade_unlock_request (academic_period_id);
CREATE INDEX idx_grade_unlock_request_assessment_id ON grade_unlock_request (assessment_id);
CREATE INDEX idx_grade_unlock_request_teacher_id ON grade_unlock_request (teacher_id);
CREATE INDEX idx_grade_unlock_request_requested_by ON grade_unlock_request (requested_by);
CREATE INDEX idx_grade_unlock_request_approved_by ON grade_unlock_request (approved_by);
CREATE INDEX idx_payment_allocation_payment_id ON payment_allocation (payment_id);
CREATE INDEX idx_payment_allocation_student_charge_id ON payment_allocation (student_charge_id);
CREATE INDEX idx_payroll_contribution_payroll_id ON payroll_contribution (payroll_id);
CREATE INDEX idx_payroll_contribution_contribution_type_id ON payroll_contribution (contribution_type_id);
CREATE INDEX idx_payroll_tax_payroll_id ON payroll_tax (payroll_id);
CREATE INDEX idx_payroll_validation_payroll_id ON payroll_validation (payroll_id);
CREATE INDEX idx_payroll_validation_validated_by ON payroll_validation (validated_by);
CREATE INDEX idx_payslip_payroll_id ON payslip (payroll_id);
CREATE INDEX idx_payslip_generated_by ON payslip (generated_by);
CREATE INDEX idx_report_card_subject_report_card_id ON report_card_subject (report_card_id);
CREATE INDEX idx_report_card_subject_subject_id ON report_card_subject (subject_id);
CREATE INDEX idx_salary_payment_payroll_id ON salary_payment (payroll_id);
CREATE INDEX idx_salary_payment_payment_method_id ON salary_payment (payment_method_id);
CREATE INDEX idx_salary_payment_cash_register_session_id ON salary_payment (cash_register_session_id);
CREATE INDEX idx_salary_payment_paid_by ON salary_payment (paid_by);
CREATE INDEX idx_schedule_exception_schedule_entry_id ON schedule_exception (schedule_entry_id);
CREATE INDEX idx_schedule_exception_replacement_teacher_id ON schedule_exception (replacement_teacher_id);
CREATE INDEX idx_schedule_exception_replacement_subject_id ON schedule_exception (replacement_subject_id);
CREATE INDEX idx_schedule_exception_replacement_room_id ON schedule_exception (replacement_room_id);
CREATE INDEX idx_schedule_exception_replacement_time_slot_id ON schedule_exception (replacement_time_slot_id);
CREATE INDEX idx_schedule_exception_created_by ON schedule_exception (created_by);
CREATE INDEX idx_trip_student_trip_id ON trip_student (trip_id);
CREATE INDEX idx_trip_student_student_id ON trip_student (student_id);
CREATE INDEX idx_trip_student_subscription_id ON trip_student (subscription_id);
CREATE INDEX idx_trip_student_boarding_stop_id ON trip_student (boarding_stop_id);
CREATE INDEX idx_trip_student_dropoff_stop_id ON trip_student (dropoff_stop_id);
CREATE INDEX idx_employee_work_unit_employee_id ON employee_work_unit (employee_id);
CREATE INDEX idx_employee_work_unit_class_session_id ON employee_work_unit (class_session_id);
CREATE INDEX idx_employee_work_unit_validated_by ON employee_work_unit (validated_by);
CREATE INDEX idx_grade_revision_grade_id ON grade_revision (grade_id);
CREATE INDEX idx_grade_revision_changed_by ON grade_revision (changed_by);
CREATE INDEX idx_grade_revision_unlock_request_id ON grade_revision (unlock_request_id);
CREATE INDEX idx_student_attendance_class_session_id ON student_attendance (class_session_id);
CREATE INDEX idx_student_attendance_student_id ON student_attendance (student_id);
CREATE INDEX idx_student_attendance_recorded_by ON student_attendance (recorded_by);
CREATE INDEX idx_student_attendance_validated_by ON student_attendance (validated_by);
CREATE INDEX idx_teacher_attendance_class_session_id ON teacher_attendance (class_session_id);
CREATE INDEX idx_teacher_attendance_teacher_id ON teacher_attendance (teacher_id);
CREATE INDEX idx_teacher_attendance_recorded_by ON teacher_attendance (recorded_by);
CREATE INDEX idx_teacher_attendance_validated_by ON teacher_attendance (validated_by);
CREATE INDEX idx_teacher_replacement_class_session_id ON teacher_replacement (class_session_id);
CREATE INDEX idx_teacher_replacement_absent_teacher_id ON teacher_replacement (absent_teacher_id);
CREATE INDEX idx_teacher_replacement_replacement_teacher_id ON teacher_replacement (replacement_teacher_id);
CREATE INDEX idx_teacher_replacement_assigned_by ON teacher_replacement (assigned_by);
CREATE INDEX idx_attendance_justification_student_attendance_id ON attendance_justification (student_attendance_id);
CREATE INDEX idx_attendance_justification_submitted_by_guardian_id ON attendance_justification (submitted_by_guardian_id);
CREATE INDEX idx_attendance_justification_reviewed_by ON attendance_justification (reviewed_by);
CREATE INDEX idx_person_name ON person (last_name, first_name);
CREATE INDEX idx_student_charge_status_due ON student_charge (status, due_date);
CREATE INDEX idx_payment_date_status ON payment (payment_date, status);
CREATE INDEX idx_schedule_entry_slot ON schedule_entry (day_of_week, time_slot_id, status);
CREATE INDEX idx_class_session_date_slot ON class_session (session_date, time_slot_id);
CREATE INDEX idx_teacher_attendance_status ON teacher_attendance (attendance_status, validation_status);
CREATE INDEX idx_student_attendance_status ON student_attendance (attendance_status, justified);
CREATE INDEX idx_work_unit_employee_date ON employee_work_unit (employee_id, work_date, status);
CREATE INDEX idx_payroll_period_status ON payroll (payroll_period_id, status);
CREATE INDEX idx_grade_student ON grade (student_id);
CREATE INDEX idx_report_card_status ON report_card (academic_period_id, status);
CREATE INDEX idx_transport_trip_date_status ON transport_trip (trip_date, status);
CREATE INDEX idx_trip_location_trip_time ON trip_location (trip_id, recorded_at);
CREATE INDEX idx_notification_recipient_unread ON notification (recipient_user_id, read_at);
CREATE INDEX idx_audit_entity_time ON audit_log (entity_type, entity_id, occurred_at);
CREATE UNIQUE INDEX uq_class_session_schedule_date ON class_session(schedule_entry_id, session_date) WHERE schedule_entry_id IS NOT NULL;
CREATE UNIQUE INDEX uq_teacher_attendance_session_teacher ON teacher_attendance(class_session_id, teacher_id);
CREATE UNIQUE INDEX uq_student_attendance_session_student ON student_attendance(class_session_id, student_id);

-- Cross-table/business rules intentionally enforced in Spring services/transactions:
-- payment allocation total = payment total (or explicit family credit)
-- allocation cannot exceed outstanding charge
-- timetable teacher/class/room overlap detection over validity periods
-- enrollment class history overlap detection
-- student belongs to class at class_session date
-- only one current school year
-- only one active/validated payroll version per employee/period
-- only one active published report card per student/period
-- transport capacity, active-trip GPS authorization and parent scope

COMMIT;
