package com.ecole.gestion_scolaire.payroll.service;

import com.ecole.gestion_scolaire.payroll.entity.PayrollEmailOutbox; import com.ecole.gestion_scolaire.payroll.repository.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.context.ApplicationContext; import org.springframework.core.io.*; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*; import org.springframework.transaction.support.*; import java.math.*; import java.text.*; import java.time.*; import java.time.format.*; import java.util.*;
@Service public class PayrollEmailService {
 private static final String LOGO_CID="slsLogo"; private static final DateTimeFormatter DATE=DateTimeFormatter.ofPattern("dd/MM/yyyy"); private static final DateTimeFormatter DT=DateTimeFormatter.ofPattern("dd/MM/yyyy à HH:mm");
 private final PayrollEmailOutboxRepository outbox; private final SalaryPaymentRepository payments; private final PayslipRepository payslips; private final ApplicationContext context;
 @Value("${app.payroll-email.enabled:true}") private boolean enabled; @Value("${app.finance-email.from:sls.school2008@gmail.com}") private String from; @Value("${app.finance-email.from-name:Groupe Scolaire Sciences et Lettres}") private String fromName;
 public PayrollEmailService(PayrollEmailOutboxRepository o,SalaryPaymentRepository p,PayslipRepository s,ApplicationContext c){outbox=o;payments=p;payslips=s;context=c;}
 public void queuePaymentReceipt(Long salaryPaymentId){var sp=payments.findById(salaryPaymentId).orElse(null);if(sp==null)return;var person=sp.getPayroll().getEmployee().getPerson();if(person.getEmail()==null||person.getEmail().isBlank())return;String to=person.getEmail().trim();if(outbox.existsBySalaryPaymentIdAndRecipientEmailIgnoreCase(salaryPaymentId,to))return;var p=sp.getPayroll();var slip=payslips.findByPayrollId(p.getId()).orElse(null);var e=new PayrollEmailOutbox();e.setRecipientEmail(to);e.setSalaryPaymentId(sp.getId());e.setSubject("Paiement de votre rémunération - "+String.format("%02d/%04d",p.getPayrollPeriod().getMonth(),p.getPayrollPeriod().getYear())+" - Groupe Scolaire Sciences et Lettres");e.setBodyHtml(layout(person.getFirstName(),sp.getAmount(),p.getNetSalary(),p.getBaseSalary(),p.getFixedPart(),p.getRegularHours(),p.getHourlyAmount(),p.getAbsenceDeduction(),sp.getPaymentMethod().getName(),sp.getReference(),sp.getPaymentDate(),p.getPayrollPeriod().getStartDate(),p.getPayrollPeriod().getEndDate(),slip==null?null:slip.getPayslipNumber()));e=outbox.save(e);schedule(e.getId());}
 private void schedule(Long id){if(!enabled)return;if(TransactionSynchronizationManager.isActualTransactionActive())TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){@Override public void afterCommit(){deliver(id);}});else deliver(id);}
 @Scheduled(initialDelayString="${app.payroll-email.dispatcher.initial-delay-ms:5000}",fixedDelayString="${app.payroll-email.dispatcher.fixed-delay-ms:30000}") public void retry(){if(!enabled)return;outbox.recoverStale(OffsetDateTime.now().minusMinutes(5));for(var e:outbox.findTop50ByStatusOrderByCreatedAtAsc("PENDING"))deliver(e.getId());for(var e:outbox.findTop50ByStatusOrderByCreatedAtAsc("FAILED"))deliver(e.getId());}
 public boolean deliver(Long id){if(!enabled)return false;if(outbox.claim(id,OffsetDateTime.now())!=1)return false;var e=outbox.findById(id).orElse(null);if(e==null)return false;try{Class<?> sc=Class.forName("org.springframework.mail.javamail.JavaMailSender");Object sender=context.getBean(sc);Object msg=sc.getMethod("createMimeMessage").invoke(sender);Class<?> mc=Class.forName("jakarta.mail.internet.MimeMessage");Class<?> hc=Class.forName("org.springframework.mail.javamail.MimeMessageHelper");Object h=hc.getConstructor(mc,boolean.class,String.class).newInstance(msg,true,"UTF-8");hc.getMethod("setTo",String.class).invoke(h,e.getRecipientEmail());hc.getMethod("setSubject",String.class).invoke(h,e.getSubject());hc.getMethod("setText",String.class,boolean.class).invoke(h,e.getBodyHtml(),true);hc.getMethod("setFrom",String.class,String.class).invoke(h,from.trim(),fromName.trim());Resource logo=new ClassPathResource("sls-logo.png");if(logo.exists())hc.getMethod("addInline",String.class,Resource.class).invoke(h,LOGO_CID,logo);sc.getMethod("send",mc).invoke(sender,msg);e.setStatus("SENT");e.setSentAt(OffsetDateTime.now());e.setLastError(null);e.setProcessingAt(null);outbox.save(e);return true;}catch(Exception ex){e.setStatus("FAILED");e.setProcessingAt(null);String m=ex.getMessage();if(m==null&&ex.getCause()!=null)m=ex.getCause().getMessage();e.setLastError(m==null?ex.getClass().getSimpleName():m.substring(0,Math.min(1800,m.length())));outbox.save(e);return false;}}
 private String layout(String firstName,BigDecimal paid,BigDecimal net,BigDecimal base,BigDecimal fixed,BigDecimal hours,BigDecimal hourlyAmount,BigDecimal absenceDeduction,String method,String ref,OffsetDateTime paymentDate,LocalDate fromDate,LocalDate toDate,String slip){return "<!doctype html><html><body style='margin:0;background:#f4f7fb;font-family:Arial,sans-serif;color:#172033'><div style='max-width:680px;margin:24px auto;background:#fff;border:1px solid #e2e8f0;border-radius:16px;overflow:hidden'><div style='background:#0f2747;padding:22px;text-align:center'><img src='cid:"+LOGO_CID+"' style='height:70px'><div style='color:#fff;font-size:20px;font-weight:700'>Groupe Scolaire Sciences et Lettres</div></div><div style='padding:28px'><h2 style='color:#0f2747'>Paiement de votre rémunération</h2><p>Bonjour "+esc(firstName)+",</p><p>Nous vous confirmons le règlement de votre rémunération pour la période du <b>"+DATE.format(fromDate)+"</b> au <b>"+DATE.format(toDate)+"</b>.</p><div style='background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:16px;line-height:1.9'><b>Salaire mensuel / base :</b> "+money(base)+"<br><b>Part fixe complémentaire :</b> "+money(fixed)+"<br><b>Heures rémunérées :</b> "+hours+" h<br><b>Montant horaire :</b> "+money(hourlyAmount)+"<br><b>Retenue manuelle pour absence :</b> "+money(absenceDeduction)+"<br><b>Net calculé :</b> "+money(net)+"<br><b>Montant versé :</b> "+money(paid)+"<br><b>Mode de paiement :</b> "+esc(method)+"<br>"+(ref==null?"":"<b>Référence :</b> "+esc(ref)+"<br>")+(slip==null?"":"<b>Bulletin :</b> "+esc(slip)+"<br>")+"<b>Date de paiement :</b> "+DT.format(paymentDate)+"</div><p style='margin-top:24px'>Votre reçu de paiement est disponible dans le système de gestion scolaire.</p><p style='margin-top:28px;color:#64748b'>Message automatique envoyé par le système de gestion scolaire.</p></div></div></body></html>";}
 private String money(BigDecimal v){NumberFormat nf=NumberFormat.getNumberInstance(Locale.FRANCE);nf.setMinimumFractionDigits(2);nf.setMaximumFractionDigits(2);return nf.format(v==null?BigDecimal.ZERO:v);} private String esc(String s){if(s==null)return "";return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
}
